force-app/main/default/objects/Contenido_Envio__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contenido_Envio__c/fields/Unidad_de_Medida__c.field-meta.xml
<CustomField>
    <fullName>Unidad_de_Medida__c</fullName>
    <label>Unidad de Medida</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unidades</fullName>
            </value>
            <value>
                <fullName>Kilogramos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Ciudad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <label>Contacto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Alto__c.field-meta.xml
<CustomField>
    <fullName>Alto__c</fullName>
    <label>Alto</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Ancho__c.field-meta.xml
<CustomField>
    <fullName>Ancho__c</fullName>
    <label>Ancho</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Breve_Descripcion_2__c.field-meta.xml
<CustomField>
    <fullName>Breve_Descripcion_2__c</fullName>
    <label>Breve Descripción 2</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Breve_Descripcion_3__c.field-meta.xml
<CustomField>
    <fullName>Breve_Descripcion_3__c</fullName>
    <label>Breve Descripción 3</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Breve_Descripcion_4__c.field-meta.xml
<CustomField>
    <fullName>Breve_Descripcion_4__c</fullName>
    <label>Breve Descripción 4</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Breve_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Breve_Descripcion__c</fullName>
    <label>Breve Descripción 1</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <formula>Direccion_Destinatario__r.Direccion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calle</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Centro_de_Costo__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_Costo__c</fullName>
    <label>Centro de Costo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <formula>Direccion_Destinatario__r.Ciudad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ciudad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Cod_Postal__c.field-meta.xml
<CustomField>
    <fullName>Cod_Postal__c</fullName>
    <formula>Direccion_Destinatario__r.Codigo_Postal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cod Postal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ID_Remitente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guías de Exportación</relationshipLabel>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Contacto_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Contacto_Destinatario__c</fullName>
    <label>Contacto Destinatario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Correo_Electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_Electronico__c</fullName>
    <label>Correo Electrónico</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/DDP__c.field-meta.xml
<CustomField>
    <fullName>DDP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DDP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Direccion_Contacto__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Contacto__c</fullName>
    <formula>Contacto__r.MailingStreet&amp;&quot; &quot;&amp; Contacto__r.MailingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dirección Contacto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Direccion_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Destinatario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre Dirección</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Direcciones__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ID_Remitente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Direcciones__c</referenceTo>
    <relationshipLabel>Guías de Exportación</relationshipLabel>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Divisa__c.field-meta.xml
<CustomField>
    <fullName>Divisa__c</fullName>
    <label>Divisa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD - U.S. Dollar</label>
            </value>
            <value>
                <fullName>CLP</fullName>
                <label>CLP - Peso Chileno</label>
            </value>
            <value>
                <fullName>EUR</fullName>
                <label>EU - Euro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Fecha_de_Envio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Envio__c</fullName>
    <label>Fecha de Envío</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/ID_Remitente__c.field-meta.xml
<CustomField>
    <fullName>ID_Remitente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID Remitente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Largo__c.field-meta.xml
<CustomField>
    <fullName>Largo__c</fullName>
    <label>Largo</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/N_de_Guia__c.field-meta.xml
<CustomField>
    <fullName>N_de_Guia__c</fullName>
    <label>Etiqueta Agente</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Otro_Remitente__c.field-meta.xml
<CustomField>
    <fullName>Otro_Remitente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Otro Remitente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Direcciones__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ID_Remitente__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Direcciones__c</referenceTo>
    <relationshipLabel>Guías de Exportación (Otra Dirección Remitente)</relationshipLabel>
    <relationshipName>Gu_as_de_Exportaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <formula>Direccion_Destinatario__r.Pais__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Paquetes__c.field-meta.xml
<CustomField>
    <fullName>Paquetes__c</fullName>
    <label>Piezas</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Peso_Agente__c.field-meta.xml
<CustomField>
    <fullName>Peso_Agente__c</fullName>
    <label>Peso Agente</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Peso_Total__c.field-meta.xml
<CustomField>
    <fullName>Peso_Total__c</fullName>
    <label>Peso Real</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Proposito_del_Envio__c.field-meta.xml
<CustomField>
    <fullName>Proposito_del_Envio__c</fullName>
    <label>Propósito del Envío</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Efectos Personales</fullName>
            </value>
            <value>
                <fullName>Documento</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>No Vendido</fullName>
            </value>
            <value>
                <fullName>Regalo</fullName>
            </value>
            <value>
                <fullName>Reparar y Devolver</fullName>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
            <value>
                <fullName>Muestra sin valor Comercial</fullName>
            </value>
            <value>
                <fullName>Regalo a China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Seguro__c.field-meta.xml
<CustomField>
    <fullName>Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Shipper_Original__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Original__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipper Original</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <formula>Contacto__r.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Telefono_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Destinatario__c</fullName>
    <label>Teléfono Destinatario</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Tipo_Contenido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Contenido__c</fullName>
    <label>Tipo Contenido</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documentos</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Unidad_de_Medida__c.field-meta.xml
<CustomField>
    <fullName>Unidad_de_Medida__c</fullName>
    <label>Unidad de Medida</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilogramos</fullName>
            </value>
            <value>
                <fullName>Libras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HE_Guia_Hot_EX.cls
public class HE_Guia_Hot_EX {
    
    public string idexp{get;set;}
    public string idp{get;set;}
    public string idc{get;set;}
    public string numguia{get;set;} 
    public string numguiacompleto{get;set;} 
    public Guias_de_Exportacion__c  gde{get;set;}
    public Direcciones__c  dir{get;set;}
    public list<Contenido_Envio__c> conenv{get;set;}
    
    public Account  acc{get;set;}
    public string ddp{get;set;}
    public string seguro{get;set;}
    public string sender{get;set;}
    public string dir_origen{get;set;}
    public string ciu_origen{get;set;}
    public string pais_origen {get;set;}
    public string contacto_origen{get;set;}
    public string telefono_origen{get;set;}
    public string fecha{get;set;}
    public string reseptor{get;set;}
    public string dir_destino{get;set;}
    public string ciu_destino{get;set;}
    public string pais_destino {get;set;}
    public string contacto_destino{get;set;}
    public string telefono_destino{get;set;}
    public string postal_destino{get;set;}
    public string otro_Remitente {get;set;}
    public string OtraDireccion {get;set;}
    public string alto{get;set;}
    public string largo{get;set;}
    public string ancho{get;set;}
    public decimal cantidad_total{get;set;}
    public decimal monto_total{get;set;}
    
    
    
    public HE_Guia_Hot_EX(ApexPages.StandardController controller){
        idexp=ApexPages.currentPage().getParameters().get('id');
        idp=ApexPages.currentPage().getParameters().get('idp');
        system.debug('idexp'+idexp); 
        gde=[select id,Name,Direccion_Destinatario__c,Contacto__c,Correo_Electronico__c,Telefono_Destinatario__c,Contacto_Destinatario__c,
             Ancho__c,Largo__c,Alto__c,Fecha_de_Envio__c,Paquetes__c,Peso_Total__c,Divisa__c,Unidad_de_Medida__c,N_de_Guia__c,
             Peso_Agente__c,Contacto__r.name,Contacto__r.email,Telefono__c,Calle__c,Ciudad__c,Pais__c,Tipo_Contenido__c,
             Shipper_Original__c,ID_Remitente__r.BillingStreet,ID_Remitente__r.BillingCity,ID_Remitente__r.name,
             ID_Remitente__r.BillingCountry,Cod_Postal__c,ID_Remitente__c,Direccion_Destinatario__r.name,CreatedDate,
             Contacto__r.MailingStreet,Contacto__r.MailingCity,Contacto__r.MailingCountry,ddp__c,Centro_de_Costo__c,
             Proposito_del_Envio__c,Seguro__c, Breve_Descripcion__c, Breve_Descripcion_2__c, Breve_Descripcion_3__c, Breve_Descripcion_4__c, Direccion_Contacto__c, Otro_Remitente__c,Otra_Direcci_n__c
             from Guias_de_Exportacion__c where id=:idexp];
        
        idc=gde.ID_Remitente__c;
        conenv= [select id,Cantidad__c,Condicion_de_Venta__c,Descripcion__c,Comentarios__c, Pais_fab__r.Cod_Pais__c,
                 Unidad_de_Medida__c,Valor_Unitario__c
                 from Contenido_Envio__c where Pickup__c=:gde.id];
        
        
        dir=[SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, 
             LastActivityDate, Cuenta__c, Direccion__c, Ciudad__c, Estado_Provincia__c,  Pais__r.name,Cod_Pais__c,
             Codigo_Postal__c, Tipo__c FROM Direcciones__c where id=:gde.Direccion_Destinatario__c];
        
        acc=[SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingCountry, BillingAddress, ShippingAddress,
             OwnerId, RUT__c, Telefono_2__c, Nombre_Fantasia__c, Haber__c, Debe__c, Saldo__c 
             FROM Account 
             WHERE Nombre_Fantasia__c =: 'Hot Express'];
        numguiacompleto=gde.name;
        numguia=(gde.name).replace('GE-','');
        otro_Remitente = gde.Otro_Remitente__c;
        
         if(gde.Otro_Remitente__c!=null){
             OtraDireccion = gde.Otra_Direcci_n__c;
         }
        else
        {
        	OtraDireccion = gde.Direccion_Contacto__c;
        }
    }
    
    public PageReference consultar(){
        system.debug('gde'+gde);
        system.debug('conenv'+conenv);
        if(gde.ddp__c==true){
            ddp='SI';   
        }else{
            ddp='NO';     
        }
        if(gde.Seguro__c==true){
            seguro='SI';   
        }else{
            seguro='NO';     
        }
        
        sender=gde.ID_Remitente__r.name;
        //  dir_origen=gde.ID_Remitente__r.BillingStreet;
        // ciu_origen=gde.ID_Remitente__r.BillingCity;
        // pais_origen=gde.ID_Remitente__r.BillingCountry;
        
        //dir_origen=gde.Contacto__r.MailingStreet;
        dir_origen=gde.Direccion_Contacto__c;
        ciu_origen=gde.Contacto__r.MailingCity;
        pais_origen=gde.ID_Remitente__r.BillingCountry;
        contacto_origen=gde.Contacto__r.name;
        telefono_origen=gde.Telefono__c;
        
        reseptor=gde.Direccion_Destinatario__r.name;
        dir_destino=gde.Calle__c;
        ciu_destino=gde.Ciudad__c;
        pais_destino=gde.Pais__c;
        postal_destino=gde.Cod_Postal__c;
        contacto_destino=gde.Contacto_Destinatario__c;
        telefono_destino=gde.Telefono_Destinatario__c;
        fecha=gde.CreatedDate.day()+'/'+gde.CreatedDate.month()+'/'+gde.CreatedDate.year();
        ancho =string.valueOf(gde.Ancho__c);
        alto=string.valueOf(gde.Alto__c);
        largo =string.valueOf(gde.Largo__c);
        
        cantidad_total=0;
        monto_total=0;
        if(conenv!=null){
            for(Contenido_Envio__c ce: conenv){
                cantidad_total=cantidad_total+ce.Cantidad__c;
                monto_total=monto_total+(ce.Cantidad__c*ce.Valor_Unitario__c);
            }
        }
        
        
        return null;
        
    }
    
    
    
}