force-app/main/default/objects/Caja__c/fields/Bag_Code__c.field-meta.xml
<CustomField>
    <fullName>Bag_Code__c</fullName>
    <externalId>true</externalId>
    <label>Bag Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Caja__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <label>Master</label>
    <referenceTo>Master__c</referenceTo>
    <relationshipName>Bags_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Codigo_Arancelario__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Bag_Code__c.field-meta.xml
<CustomField>
    <fullName>Bag_Code__c</fullName>
    <label>Bag Code</label>
    <referenceTo>Caja__c</referenceTo>
    <relationshipLabel>Detalles Guías</relationshipLabel>
    <relationshipName>Detalles_Gu_as</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/DIP_Confecionada__c.field-meta.xml
<CustomField>
    <fullName>DIP_Confecionada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DIP Confecionada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Estado_Guia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Guia__c</fullName>
    <label>Estado Guía</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documental</fullName>
            </value>
            <value>
                <fullName>Menor a 30</fullName>
            </value>
            <value>
                <fullName>Facturada</fullName>
            </value>
            <value>
                <fullName>Abandonado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Retenido por RUT</fullName>
            </value>
            <value>
                <fullName>Retenido por Aduana</fullName>
            </value>
            <value>
                <fullName>Retenido por Visación</fullName>
            </value>
            <value>
                <fullName>Retenido en escaner</fullName>
            </value>
            <value>
                <fullName>En cadena de custodia</fullName>
            </value>
            <value>
                <fullName>Paquete No Recibido</fullName>
            </value>
            <value>
                <fullName>Retenido por error ISP</fullName>
            </value>
            <value>
                <fullName>Retenido por peso</fullName>
            </value>
            <value>
                <fullName>Sobrante</fullName>
            </value>
            <value>
                <fullName>Alto valor</fullName>
            </value>
            <value>
                <fullName>RUT no conseguido Retenido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <label>Master</label>
    <referenceTo>Master__c</referenceTo>
    <relationshipName>Detalles_Manifiestos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Nombre_Cod_Arancelario__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Cod_Arancelario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre Cod Arancelario</label>
    <referenceTo>Codigo_Arancelario__c</referenceTo>
    <relationshipLabel>Detalles Guías</relationshipLabel>
    <relationshipName>Detalles_Manifiestos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Pieces__c.field-meta.xml
<CustomField>
    <fullName>Pieces__c</fullName>
    <description>Número de paquetes del registro</description>
    <label>Pieces</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por Cobrar</fullName>
                <default>true</default>
                <label>Por Cobrar</label>
            </value>
            <value>
                <fullName>Pagada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Anulada NC</fullName>
            </value>
            <value>
                <fullName>Incobrable Otros</fullName>
            </value>
            <value>
                <fullName>Incobrable Dicom</fullName>
            </value>
            <value>
                <fullName>Abonada</fullName>
            </value>
            <value>
                <fullName>Rechazada SII</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_de_Servicio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Servicio__c</fullName>
    <label>Tipo de Servicio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IMPORT</fullName>
            </value>
            <value>
                <fullName>EXPORT</fullName>
            </value>
            <value>
                <fullName>CARGO</fullName>
            </value>
            <value>
                <fullName>NACIONAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master__c/fields/Aeropuerto_Destino__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto_Destino__c</fullName>
    <label>Aeropuerto Destino</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Aeropuerto_Origen__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto_Origen__c</fullName>
    <label>Aeropuerto Origen</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Masters</relationshipLabel>
    <relationshipName>Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Recepcionado</fullName>
                <default>true</default>
                <label>Recepcionado</label>
            </value>
            <value>
                <fullName>En Digitación</fullName>
            </value>
            <value>
                <fullName>Enviado a Atrex</fullName>
            </value>
            <value>
                <fullName>Depurado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master__c/fields/Fecha_Recepcion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Recepcion__c</fullName>
    <label>Fecha Recepción</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Fecha_Vuelo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Vuelo__c</fullName>
    <label>Fecha Vuelo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Master_AirwayBill__c.field-meta.xml
<CustomField>
    <fullName>Master_AirwayBill__c</fullName>
    <externalId>true</externalId>
    <label>Master AirwayBill</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HE_Generar_DIPs_ControllerTEST.cls
@istest(SeeAllData=false)

public class HE_Generar_DIPs_ControllerTEST {
 static testMethod void test1() {
    
     Account  acc=new Account();
     acc.Name='1211';
     insert acc;
     Factura__c  f=new Factura__c();
     f.Cuenta__c=acc.id;
     f.Tipo_de_Servicio__c='IMPORT';
     insert f;
     
     Master__c  ma=new Master__c();
     ma.Cuenta__c=acc.id;
     ma.Aeropuerto_Destino__c='stg';
     ma.Aeropuerto_Origen__c='stg';
     ma.Fecha_Recepcion__c=date.today();
     ma.Fecha_Vuelo__c=date.today();
     ma.Master_AirwayBill__c='1234';
     ma.name='1234';
     ma.Estado__c='activo';
     insert ma;
     system.debug('ma'+ma);
     
     Caja__c  bc=new Caja__c();
     bc.name='543245';
     bc.Master__c=ma.id;
     bc.Bag_Code__c='543245';
     insert bc;
     Codigo_Arancelario__c ca=new Codigo_Arancelario__c();
     ca.Name='usb';
     ca.Codigo__c='122412';
     insert ca;
     Detalles_Master__c  dm=new Detalles_Master__c();
     dm.Name='13452';
     dm.Master__c=ma.id;
     dm.Bag_Code__c=bc.id;
     dm.Estado_Guia__c='Documental';
     dm.DIP_Confecionada__c=false;
     dm.Nombre_Cod_Arancelario__c=ca.id;
     dm.Pieces__c=1;
     insert dm;
     system.debug('dm'+dm);
     
      apexPages.Currentpage().getParameters().put('id',dm.Master__c);
      ApexPages.StandardController ast=new ApexPages.StandardController(ma);   
      HE_Generar_DIPs_Controler  he=new HE_Generar_DIPs_Controler(ast);   
     he.Generar_DIP();
     
 }
}