force-app/main/default/objects/Costo_Solicitud_Pickup__c/fields/Solicitud_de_Pickup__c.field-meta.xml
<CustomField>
    <fullName>Solicitud_de_Pickup__c</fullName>
    <label>Solicitud de Pickup</label>
    <referenceTo>Solicitud_de_Pickup__c</referenceTo>
    <relationshipName>Costos_Solicitudes_Pickup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Ciudad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Cod_Pais__c.field-meta.xml
<CustomField>
    <fullName>Cod_Pais__c</fullName>
    <formula>Pais__r.Cod_Pais__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cod País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>105</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Estado_Provincia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Provincia__c</fullName>
    <label>Estado/ Provincia</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Zona_Hot__c.field-meta.xml
<CustomField>
    <fullName>Zona_Hot__c</fullName>
    <formula>Text (Pais__r.Zona_Hot__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zona Hot</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Masters</relationshipLabel>
    <relationshipName>Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Cod_Pais__c.field-meta.xml
<CustomField>
    <fullName>Cod_Pais__c</fullName>
    <label>Cod País</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Nombre_Zonas__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Zonas__c</fullName>
    <label>Nombre Zona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUR AMERICA 1</fullName>
            </value>
            <value>
                <fullName>SUR AMERICA 2</fullName>
            </value>
            <value>
                <fullName>CENTRO Y NORTE AMERICA, CARIBE</fullName>
            </value>
            <value>
                <fullName>EUROPA</fullName>
            </value>
            <value>
                <fullName>ASIA</fullName>
            </value>
            <value>
                <fullName>RESTO DEL MUNDO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Zona_DHL__c.field-meta.xml
<CustomField>
    <fullName>Zona_DHL__c</fullName>
    <label>Zona DHL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Zona 1</fullName>
            </value>
            <value>
                <fullName>Zona 2</fullName>
            </value>
            <value>
                <fullName>Zona 3</fullName>
            </value>
            <value>
                <fullName>Zona 4</fullName>
            </value>
            <value>
                <fullName>Zona 5</fullName>
            </value>
            <value>
                <fullName>Zona 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Zona_Fedex__c.field-meta.xml
<CustomField>
    <fullName>Zona_Fedex__c</fullName>
    <label>Zona Fedex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Zona 1</fullName>
            </value>
            <value>
                <fullName>Zona 2</fullName>
            </value>
            <value>
                <fullName>Zona 3</fullName>
            </value>
            <value>
                <fullName>Zona 4</fullName>
            </value>
            <value>
                <fullName>Zona 5</fullName>
            </value>
            <value>
                <fullName>Zona 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Zona_Hot__c.field-meta.xml
<CustomField>
    <fullName>Zona_Hot__c</fullName>
    <label>Zona Hot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zona 1</fullName>
            </value>
            <value>
                <fullName>Zona 2</fullName>
            </value>
            <value>
                <fullName>Zona 3</fullName>
            </value>
            <value>
                <fullName>Zona 4</fullName>
            </value>
            <value>
                <fullName>Zona 5</fullName>
            </value>
            <value>
                <fullName>Zona 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Agente__c.field-meta.xml
<CustomField>
    <fullName>Agente__c</fullName>
    <label>Agente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>FedEx</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Alto_cm__c.field-meta.xml
<CustomField>
    <fullName>Alto_cm__c</fullName>
    <label>Alto (cm)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Ancho_cm__c.field-meta.xml
<CustomField>
    <fullName>Ancho_cm__c</fullName>
    <label>Ancho (cm)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Cantidad_de_Paquetes__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Paquetes__c</fullName>
    <label>Cantidad de Paquetes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <formula>Direccion_Remitente__r.Ciudad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ciudad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Cod_Pais__c.field-meta.xml
<CustomField>
    <fullName>Cod_Pais__c</fullName>
    <formula>Direccion_Remitente__r.Cod_Pais__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cod País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <formula>Direccion_Remitente__r.Codigo_Postal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código Postal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Solicitudes de Pickup</relationshipLabel>
    <relationshipName>Guias_Exportacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Direccion_Remitente__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Remitente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dirección Remitente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Direcciones__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Direcciones__c</referenceTo>
    <relationshipLabel>Solicitudes de Pickup</relationshipLabel>
    <relationshipName>Gu_as_Exportaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Embalaje_HOT__c.field-meta.xml
<CustomField>
    <fullName>Embalaje_HOT__c</fullName>
    <label>Embalaje HOT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sobre</fullName>
            </value>
            <value>
                <fullName>Pack</fullName>
            </value>
            <value>
                <fullName>Cajas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Largo_cm__c.field-meta.xml
<CustomField>
    <fullName>Largo_cm__c</fullName>
    <label>Largo (cm)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <formula>Direccion_Remitente__r.Pais__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Peso_Agente__c.field-meta.xml
<CustomField>
    <fullName>Peso_Agente__c</fullName>
    <label>Peso Agente</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Peso_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Peso_Cliente__c</fullName>
    <label>Peso Cliente</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Peso_Total__c.field-meta.xml
<CustomField>
    <fullName>Peso_Total__c</fullName>
    <label>Peso Total</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Telefono_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Destinatario__c</fullName>
    <label>Teléfono Destinatario</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Zona_DHL__c.field-meta.xml
<CustomField>
    <fullName>Zona_DHL__c</fullName>
    <formula>text( Direccion_Remitente__r.Pais__r.Zona_DHL__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zona DHL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Zona_Fedex__c.field-meta.xml
<CustomField>
    <fullName>Zona_Fedex__c</fullName>
    <formula>text(Direccion_Remitente__r.Pais__r.Zona_Fedex__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zona Fedex</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pickup__c/fields/Zona_HOT__c.field-meta.xml
<CustomField>
    <fullName>Zona_HOT__c</fullName>
    <formula>Direccion_Remitente__r.Zona_Hot__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zona HOT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HE_listado_clientes_ImporTEST.cls
@istest(SeeAllData=false)
public class HE_listado_clientes_ImporTEST {
static testMethod void test1() {
        
        Account  acc=new Account();
        acc.Name='1211';
        insert acc;
        
        
        Pais__c p=new Pais__c();
        p.Name='ARGENTINA';
        p.Cod_Pais__c='AR';
        
        p.Nombre_Zonas__c='SUR AMERICA 1';
        p.Zona_DHL__c='Zona 1';
        p.Zona_Fedex__c='Zona 1';
        p.Zona_Hot__c='Zona 1';
        insert p;
        
        Direcciones__c d=new Direcciones__c();
        d.Name='direccion test';
        d.Cuenta__c=acc.id;
        d.Direccion__c='isidora goyenechea 3000';
        d.Ciudad__c='Buenos Aires';
        d.Estado_Provincia__c='Buenos Aires';
        d.Codigo_Postal__c='7550653';
        d.Pais__c=p.id;
        insert d;
        
         Solicitud_de_Pickup__c ge=new Solicitud_de_Pickup__c();
        ge.Cuenta__c=acc.id;
        ge.Agente__c='DHL';
        ge.Peso_Cliente__c=8;
        ge.Peso_Agente__c=8;
        ge.Embalaje_HOT__c='cajas'; 
        ge.Telefono_Destinatario__c='+5698765442';
        ge.Fecha_de_Envio__c=system.today();
        ge.Cantidad_de_Paquetes__c=3;
        ge.Largo_cm__c=2;
        ge.Ancho_cm__c=2;
        ge.Alto_cm__c=2;
        ge.Peso_Total__c=8;
        ge.Direccion_Remitente__c=d.id;
        ge.Direccion_de_Entrega__c=d.id;
        ge.Contacto_Destinatario__c='contacto test';
        ge.Guia_validada__c=true;
        insert ge;
        Contenido_Importacion_Agente__c  con=new Contenido_Importacion_Agente__c();
         
        con.Importacion_Agente__c=ge.id;
        con.Descripcion__c='vino';
        con.Pais_de_Fabricacion__c =p.id;
        con.Cantidad__c=1;
        con.Unidad_de_Medida__c='Unidades';
        con.Valor_Unitario__c=15;
        insert con;
     
     Costo__c c=new Costo__c();
     c.Name='comvustible';
     insert c;
     
       Costo_Solicitud_Pickup__c cosinp=new Costo_Solicitud_Pickup__c();
        cosinp.Costo__c=c.id;
        cosinp.Valor__c=8;
        cosinp.Solicitud_de_Pickup__c=ge.Id;
        cosinp.Estado__c= 'Pendiente de Facturar';
        insert cosinp;
        
        //  apexPages.Currentpage().getParameters().put('id',dm.Master__c);
        //  ApexPages.StandardController ast=new ApexPages.StandardController(ma);   
        
        apexPages.Currentpage().getParameters().put('FI','01-06-2019');
        apexPages.Currentpage().getParameters().put('FN','01-06-2025');
        apexPages.Currentpage().getParameters().put('V','600');
        apexPages.Currentpage().getParameters().put('td','1');
        apexPages.Currentpage().getParameters().put('tc','');
        apexPages.Currentpage().getParameters().put('ida',acc.id);
        apexPages.Currentpage().getParameters().put('idcon','');
        apexPages.Currentpage().getParameters().put('ps','');
        apexPages.Currentpage().getParameters().put('zon','');
        HE_listado_clientes_Impor  he=new HE_listado_clientes_Impor();   
        he.Obtenerclientes();
        string  datos='[{"id":"0015A000026wpWEQAY","name":"MUNDO DEL VINO ISIDORA","RUT":"96856980-5","comuna":"santiago","direccion":"isidora goyenechea  3000","contadorpendientes":1,"oc":"","comentario":"","listarguias":[{"idguia":"'+ge.id+'","idproducto":"GE-0000000019","pais_destino":"ARGENTINA","tipo":"Mercancías","fecha":"2020-06-17","montoUSD":"297.60","montoCLP":"59520"}]},{"id":"0015A000026wpaNQAQ","name":"VINOS RAVANAL LTDA.","RUT":"76242685-4","comuna":"San Fernando","direccion":"OSCAR GAJARDO S/N Placilla","contadorpendientes":1,"oc":"","comentario":"","listarguias":[{"idguia":"'+ge.id+'","idproducto":"GE-0000000025","pais_destino":"ESTADOS UNIDOS","tipo":"Mercancías","fecha":"2020-06-11","montoUSD":"100.00","montoCLP":"20000"},{"idguia":"'+ge.id+'","idproducto":"GE-0000000022","pais_destino":"ESTADOS UNIDOS","tipo":"Mercancías","fecha":"2020-06-11","montoUSD":"137.22","montoCLP":"27444"}]}]';
        apexPages.Currentpage().getParameters().put('datos',datos);
        he.facrturar();
    
    } 
}