force-app/main/default/objects/Codigo_Arancelario__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Codigo_Arancelario__c/fields/Descripcion_Ingles__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Ingles__c</fullName>
    <label>Descripción Inglés</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/DIP_Confecionada__c.field-meta.xml
<CustomField>
    <fullName>DIP_Confecionada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DIP Confecionada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Estado_Guia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Guia__c</fullName>
    <label>Estado Guía</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documental</fullName>
            </value>
            <value>
                <fullName>Menor a 30</fullName>
            </value>
            <value>
                <fullName>Facturada</fullName>
            </value>
            <value>
                <fullName>Abandonado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Master_Importacion__c.field-meta.xml
<CustomField>
    <fullName>Master_Importacion__c</fullName>
    <label>Master Importación</label>
    <referenceTo>Master_Importacion__c</referenceTo>
    <relationshipLabel>Detalles Guías Importación</relationshipLabel>
    <relationshipName>Detalles_Gu_as_Importaci_n</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Valija__c.field-meta.xml
<CustomField>
    <fullName>Valija__c</fullName>
    <label>Valija</label>
    <referenceTo>Valija__c</referenceTo>
    <relationshipLabel>Detalles Guías Importación</relationshipLabel>
    <relationshipName>Detalles_Guias_Importaci_n</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por Cobrar</fullName>
                <default>true</default>
                <label>Por Cobrar</label>
            </value>
            <value>
                <fullName>Pagada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Anulada NC</fullName>
            </value>
            <value>
                <fullName>Incobrable Otros</fullName>
            </value>
            <value>
                <fullName>Incobrable Dicom</fullName>
            </value>
            <value>
                <fullName>Abonada</fullName>
            </value>
            <value>
                <fullName>Rechazada SII</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_de_Servicio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Servicio__c</fullName>
    <label>Tipo de Servicio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IMPORT</fullName>
            </value>
            <value>
                <fullName>EXPORT</fullName>
            </value>
            <value>
                <fullName>CARGO</fullName>
            </value>
            <value>
                <fullName>NACIONAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Importacion__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Importaciones</relationshipLabel>
    <relationshipName>Master_Importaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Importacion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Recepcionado</fullName>
            </value>
            <value>
                <fullName>En Digitación</fullName>
            </value>
            <value>
                <fullName>Enviado a Atrex</fullName>
            </value>
            <value>
                <fullName>Depurado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Importacion__c/fields/Fecha_Recepcion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Recepcion__c</fullName>
    <label>Fecha Recepción</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Importacion__c/fields/Master_AirwayBill__c.field-meta.xml
<CustomField>
    <fullName>Master_AirwayBill__c</fullName>
    <externalId>true</externalId>
    <label>Master AirwayBill</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valija__c/fields/Master_Importacion__c.field-meta.xml
<CustomField>
    <fullName>Master_Importacion__c</fullName>
    <label>Master Importación</label>
    <referenceTo>Master_Importacion__c</referenceTo>
    <relationshipLabel>Valijas</relationshipLabel>
    <relationshipName>Valijas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HE_Codigo_Aduanero_ImportacionesTEST.cls
@istest 
public class HE_Codigo_Aduanero_ImportacionesTEST {
static testMethod void test1() {
    Account  acc=new Account();
     acc.Name='1211';
     insert acc;
     Factura__c  f=new Factura__c();
     f.Cuenta__c=acc.id;
     f.Tipo_de_Servicio__c='IMPORT';
     insert f;
     
     Master_Importacion__c  ma=new Master_Importacion__c();
     ma.Cuenta__c=acc.id;
     ma.Aeropuerto_Destino__c='stg';
     ma.Aeropuerto_Origen__c='stg';
     ma.Fecha_Recepcion__c=date.today();
     ma.Fecha_Vuelo__c=date.today();
     ma.Master_AirwayBill__c='1234';
     ma.name='1234';
     ma.Estado__c='activo';
     insert ma;
     system.debug('ma'+ma);
     
     Valija__c  bc=new Valija__c();
     bc.name='543245';
     bc.Master_Importacion__c=ma.id; 
     insert bc;
     Codigo_Arancelario__c ca=new Codigo_Arancelario__c();
     ca.Name='usb';
     ca.Codigo__c='122412';
     ca.Descripcion_Ingles__c='usb';
     insert ca;
     Detalles_Guias_Importacion__c  dm=new Detalles_Guias_Importacion__c();
     dm.Name='13452';
     dm.Master_Importacion__c=ma.id;
     dm.Valija__c=bc.id;
     dm.Estado_Guia__c='Documental';
     dm.DIP_Confecionada__c=false; 
     dm.Descripcion__c='usb';
     insert dm;
    list<id>  ds=new  list<id>();
    ds.add(dm.id);
    HE_Codigo_Aduanero_Importaciones  heca=new HE_Codigo_Aduanero_Importaciones();
    HE_Codigo_Aduanero_Importaciones.HE_codigo_aduanero(ds);
}
    
}