force-app/main/default/objects/Codigo_Arancelario__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Cod_Arancelario__c.field-meta.xml
<CustomField>
    <fullName>Cod_Arancelario__c</fullName>
    <formula>Nombre_Cod_Arancelario__r.Codigo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cod Arancelario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/DIP_Confecionada__c.field-meta.xml
<CustomField>
    <fullName>DIP_Confecionada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DIP Confecionada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Estado_Guia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Guia__c</fullName>
    <label>Estado Guía</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documental</fullName>
            </value>
            <value>
                <fullName>Menor a 30</fullName>
            </value>
            <value>
                <fullName>Facturada</fullName>
            </value>
            <value>
                <fullName>Abandonado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Master_Importacion__c.field-meta.xml
<CustomField>
    <fullName>Master_Importacion__c</fullName>
    <label>Master Importación</label>
    <referenceTo>Master_Importacion__c</referenceTo>
    <relationshipLabel>Detalles Guías Importación</relationshipLabel>
    <relationshipName>Detalles_Gu_as_Importaci_n</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Nombre_Cod_Arancelario__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Cod_Arancelario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre Cod Arancelario</label>
    <referenceTo>Codigo_Arancelario__c</referenceTo>
    <relationshipLabel>Detalles Guías Importación</relationshipLabel>
    <relationshipName>Detalles_Gu_as_Importaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Pais_de_Adquisicion__c.field-meta.xml
<CustomField>
    <fullName>Pais_de_Adquisicion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País de Adquisición</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipName>Detalles_Gu_as_Importaci_n1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Pais_de_Origen__c.field-meta.xml
<CustomField>
    <fullName>Pais_de_Origen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País de Origen</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipName>Detalles_Gu_as_Importaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Puerto_de_Destino__c.field-meta.xml
<CustomField>
    <fullName>Puerto_de_Destino__c</fullName>
    <label>Puerto de Destino</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Importacion__c/fields/Master_AirwayBill__c.field-meta.xml
<CustomField>
    <fullName>Master_AirwayBill__c</fullName>
    <externalId>true</externalId>
    <label>Master AirwayBill</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Cod_Pais__c.field-meta.xml
<CustomField>
    <fullName>Cod_Pais__c</fullName>
    <label>Cod País</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HE_Generar_DIPs_Importacion_Controller.cls
public class HE_Generar_DIPs_Importacion_Controller {
  public string idm{get;set;}
   // public list<tempuriOrg.Estruct_Envio> listado_estado{get;set;}
    public HE_Generar_DIPs_Importacion_Controller(ApexPages.StandardController controller){
           idm = ApexPages.currentPage().getParameters().get('id');
    }
    
    public PageReference Generar_DIP() {
        system.debug('idm'+idm);
        string guia='Documental';
         List<Detalles_Guias_Importacion__c> detmast;
        if(!test.isRunningTest()){
         detmast = [SELECT Id,name, Master_Importacion__r.Name,  Puerto_de_Destino__c,Master_Importacion__r.Aeropuerto_Origen__c, Cod_Arancelario__c,DIP_Confecionada__c,Master_Importacion__r.Master_AirwayBill__c,
                    Nombre_Cod_Arancelario__r.Codigo__c, Nombre_Cod_Arancelario__r.Name,Pais_de_Origen__r.Cod_Pais__c,Pais_de_Adquisicion__r.Cod_Pais__c
                                            FROM Detalles_Guias_Importacion__c where Master_Importacion__c=:idm  and DIP_Confecionada__c=:false  and Estado_Guia__c=:guia];
        }else{
         detmast = [SELECT Id,name, Master_Importacion__r.Name,  Puerto_de_Destino__c,Master_Importacion__r.Aeropuerto_Origen__c, Cod_Arancelario__c,DIP_Confecionada__c,Master_Importacion__r.Master_AirwayBill__c,
                    Nombre_Cod_Arancelario__r.Codigo__c,Nombre_Cod_Arancelario__r.Name,Pais_de_Origen__r.Cod_Pais__c,Pais_de_Adquisicion__r.Cod_Pais__c
                                            FROM Detalles_Guias_Importacion__c where Master_Importacion__c=:idm  and DIP_Confecionada__c=:false];
        }
            system.debug('detmast'+detmast);
        string finalstr='';
        for(Detalles_Guias_Importacion__c dt: detmast){
            
     
       // string recordString = dt.Master_Importacion__r.Name+','+dt.name+','+''+dt.Puerto_de_Destino__c+','+','+dt.Master_Importacion__r.Aeropuerto_Origen__c+','+dt.Cod_Arancelario__c+'\n';
        string recordString = dt.Master_Importacion__r.Name+','+dt.name+','+','+dt.Pais_de_Adquisicion__r.Cod_Pais__c+','+dt.Pais_de_Origen__r.Cod_Pais__c+','+dt.Nombre_Cod_Arancelario__r.Codigo__c+','+','+dt.Nombre_Cod_Arancelario__r.Name+'\n';
         
            finalstr = finalstr +recordString;
        }
        
         for(integer i=0;i<detmast.size();i++){
              detmast.get(i).DIP_Confecionada__c=true;
         }
        update detmast;
        blob csvBlob = Blob.valueOf(finalstr);
        Attachment csv=new Attachment();
        csv.Body=csvBlob;
        csv.ParentId=idm;
        csv.Name= detmast.get(0).Master_Importacion__r.Master_AirwayBill__c+'_DIPs.xls';
        insert csv;
        Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        
        string csvname= detmast.get(0).Master_Importacion__r.Name+'_DIPs.xls';
        csvAttc.setFileName(csvname);
        csvAttc.setBody(csvBlob);
        Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
        String[] toAddresses = new list<string> {'jcarvajal@nectia.com'};
            String subject ='Detalles_Guias_Importacion__c CSV';
        email.setSubject(subject);
        email.setToAddresses( toAddresses );
        email.setPlainTextBody('Detalles_Guias_Importacion__c_CSV ');
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
          pageReference p = new PageReference('/'+idm);
            
        
        return p; 
    }
}