force-app/main/default/objects/Codigo_Arancelario__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/DIP_Confecionada__c.field-meta.xml
<CustomField>
    <fullName>DIP_Confecionada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DIP Confecionada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Estado_Guia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Guia__c</fullName>
    <label>Estado Guía</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documental</fullName>
            </value>
            <value>
                <fullName>Menor a 30</fullName>
            </value>
            <value>
                <fullName>Facturada</fullName>
            </value>
            <value>
                <fullName>Abandonado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Retenido por RUT</fullName>
            </value>
            <value>
                <fullName>Retenido por Aduana</fullName>
            </value>
            <value>
                <fullName>Retenido por Visación</fullName>
            </value>
            <value>
                <fullName>Retenido en escaner</fullName>
            </value>
            <value>
                <fullName>En cadena de custodia</fullName>
            </value>
            <value>
                <fullName>Paquete No Recibido</fullName>
            </value>
            <value>
                <fullName>Retenido por error ISP</fullName>
            </value>
            <value>
                <fullName>Retenido por peso</fullName>
            </value>
            <value>
                <fullName>Sobrante</fullName>
            </value>
            <value>
                <fullName>Alto valor</fullName>
            </value>
            <value>
                <fullName>RUT no conseguido Retenido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <label>Master</label>
    <referenceTo>Master__c</referenceTo>
    <relationshipName>Detalles_Manifiestos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Nombre_Cod_Arancelario__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Cod_Arancelario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre Cod Arancelario</label>
    <referenceTo>Codigo_Arancelario__c</referenceTo>
    <relationshipLabel>Detalles Guías</relationshipLabel>
    <relationshipName>Detalles_Manifiestos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Puerto_de_Destino__c.field-meta.xml
<CustomField>
    <fullName>Puerto_de_Destino__c</fullName>
    <label>Puerto de Destino</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Aeropuerto_Origen__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto_Origen__c</fullName>
    <label>Aeropuerto Origen</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Master_AirwayBill__c.field-meta.xml
<CustomField>
    <fullName>Master_AirwayBill__c</fullName>
    <externalId>true</externalId>
    <label>Master AirwayBill</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HE_Generar_DIPs_Controler.cls
public class HE_Generar_DIPs_Controler {
 public string idm{get;set;}
    public list<tempuriOrg.Estruct_Envio> listado_estado{get;set;}
    public HE_Generar_DIPs_Controler(ApexPages.StandardController controller){
           idm = ApexPages.currentPage().getParameters().get('id');
    }
    
    public PageReference Generar_DIP() {
        system.debug('idm'+idm);
        string guia='Documental';
         List<Detalles_Master__c> detmast;
        if(!test.isRunningTest()){
         detmast = [SELECT Id,name, Master__r.Name,  Puerto_de_Destino__c,Master__r.Aeropuerto_Origen__c, Cod_Arancelario__c,Nombre_Cod_Arancelario__r.Codigo__c,
                    Nombre_Cod_Arancelario__r.Name,DIP_Confecionada__c,Master__r.Master_AirwayBill__c,Descripcion__c
                                            FROM Detalles_Master__c where Master__c=:idm  and DIP_Confecionada__c=:false  and Estado_Guia__c=:guia];
        }else{
         detmast = [SELECT Id,name, Master__r.Name,  Puerto_de_Destino__c,Master__r.Aeropuerto_Origen__c, Cod_Arancelario__c,DIP_Confecionada__c,Master__r.Master_AirwayBill__c,
                    Nombre_Cod_Arancelario__r.Codigo__c,Nombre_Cod_Arancelario__r.Name,Descripcion__c
                                            FROM Detalles_Master__c where Master__c=:idm  and DIP_Confecionada__c=:false];
        }
            system.debug('detmast'+detmast);
        string finalstr='';
        for(Detalles_Master__c dt: detmast){
            
     
      //  string recordString = dt.Master__r.Name+','+dt.name+','+','+dt.Puerto_de_Destino__c+','+dt.Master__r.Aeropuerto_Origen__c+','+dt.Nombre_Cod_Arancelario__r.Codigo__c+','+','+dt.Nombre_Cod_Arancelario__r.Name+'\n';
       string recordString = dt.Master__r.Name+','+dt.name+','+','+'HK'+','+'HK'+','+dt.Nombre_Cod_Arancelario__r.Codigo__c+','+','+dt.Descripcion__c+'\n';
            finalstr = finalstr +recordString;
        }
        
         for(integer i=0;i<detmast.size();i++){
              detmast.get(i).DIP_Confecionada__c=true;
         }
        update detmast;
        blob csvBlob = Blob.valueOf(finalstr);
        Attachment csv=new Attachment();
        csv.Body=csvBlob;
        csv.ParentId=idm;
        csv.Name= detmast.get(0).Master__r.Master_AirwayBill__c+'_DIPs.xls';
        insert csv;
        Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        
        string csvname= detmast.get(0).Master__r.Name+'_DIPs.xls';
        csvAttc.setFileName(csvname);
        csvAttc.setBody(csvBlob);
        Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
        String[] toAddresses = new list<string> {'jcarvajal@nectia.com'};
            String subject ='Detalles_Master__c CSV';
        email.setSubject(subject);
        email.setToAddresses( toAddresses );
        email.setPlainTextBody('Detalles_Master__c_CSV ');
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
          pageReference p = new PageReference('/'+idm);
            
        
        return p; 
    }
}