force-app/main/default/objects/Contacto_HotExpress__mdt/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contenido_Envio__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contenido_Envio__c/fields/Unidad_de_Medida__c.field-meta.xml
<CustomField>
    <fullName>Unidad_de_Medida__c</fullName>
    <label>Unidad de Medida</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unidades</fullName>
            </value>
            <value>
                <fullName>Kilogramos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Ciudad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <label>Contacto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Alto__c.field-meta.xml
<CustomField>
    <fullName>Alto__c</fullName>
    <label>Alto</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Ancho__c.field-meta.xml
<CustomField>
    <fullName>Ancho__c</fullName>
    <label>Ancho</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Breve_Descripcion_2__c.field-meta.xml
<CustomField>
    <fullName>Breve_Descripcion_2__c</fullName>
    <label>Breve Descripción 2</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Breve_Descripcion_3__c.field-meta.xml
<CustomField>
    <fullName>Breve_Descripcion_3__c</fullName>
    <label>Breve Descripción 3</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Breve_Descripcion_4__c.field-meta.xml
<CustomField>
    <fullName>Breve_Descripcion_4__c</fullName>
    <label>Breve Descripción 4</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Breve_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Breve_Descripcion__c</fullName>
    <label>Breve Descripción 1</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <formula>Direccion_Destinatario__r.Direccion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calle</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <formula>Direccion_Destinatario__r.Ciudad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ciudad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ID_Remitente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guías de Exportación</relationshipLabel>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Contacto_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Contacto_Destinatario__c</fullName>
    <label>Contacto Destinatario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Correo_Electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_Electronico__c</fullName>
    <label>Correo Electrónico</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/DDP__c.field-meta.xml
<CustomField>
    <fullName>DDP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DDP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Direccion_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Destinatario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre Dirección</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Direcciones__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ID_Remitente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Direcciones__c</referenceTo>
    <relationshipLabel>Guías de Exportación</relationshipLabel>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Divisa__c.field-meta.xml
<CustomField>
    <fullName>Divisa__c</fullName>
    <label>Divisa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD - U.S. Dollar</label>
            </value>
            <value>
                <fullName>CLP</fullName>
                <label>CLP - Peso Chileno</label>
            </value>
            <value>
                <fullName>EUR</fullName>
                <label>EU - Euro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Envio_Particular_a_Particular__c.field-meta.xml
<CustomField>
    <fullName>Envio_Particular_a_Particular__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Envió Particular a Particular</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Fecha_de_Envio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Envio__c</fullName>
    <label>Fecha de Envío</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/FrxTaxID__c.field-meta.xml
<CustomField>
    <fullName>FrxTaxID__c</fullName>
    <formula>Direccion_Destinatario__r.Tax_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/ID_Remitente__c.field-meta.xml
<CustomField>
    <fullName>ID_Remitente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID Remitente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Largo__c.field-meta.xml
<CustomField>
    <fullName>Largo__c</fullName>
    <label>Largo</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/N_de_Guia__c.field-meta.xml
<CustomField>
    <fullName>N_de_Guia__c</fullName>
    <label>Etiqueta Agente</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Otro_Remitente__c.field-meta.xml
<CustomField>
    <fullName>Otro_Remitente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Otro Remitente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Direcciones__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ID_Remitente__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Direcciones__c</referenceTo>
    <relationshipLabel>Guías de Exportación (Otra Dirección Remitente)</relationshipLabel>
    <relationshipName>Gu_as_de_Exportaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <formula>Direccion_Destinatario__r.Pais__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Paquetes__c.field-meta.xml
<CustomField>
    <fullName>Paquetes__c</fullName>
    <label>Piezas</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Peso_Agente__c.field-meta.xml
<CustomField>
    <fullName>Peso_Agente__c</fullName>
    <label>Peso Agente</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Peso_Total__c.field-meta.xml
<CustomField>
    <fullName>Peso_Total__c</fullName>
    <label>Peso Real</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Proposito_del_Envio__c.field-meta.xml
<CustomField>
    <fullName>Proposito_del_Envio__c</fullName>
    <label>Propósito del Envío</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Efectos Personales</fullName>
            </value>
            <value>
                <fullName>Documento</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>No Vendido</fullName>
            </value>
            <value>
                <fullName>Regalo</fullName>
            </value>
            <value>
                <fullName>Reparar y Devolver</fullName>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
            <value>
                <fullName>Muestra sin valor Comercial</fullName>
            </value>
            <value>
                <fullName>Regalo a China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Shipper_Original__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Original__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipper Original</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <formula>Contacto__r.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Telefono_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Destinatario__c</fullName>
    <label>Teléfono Destinatario</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Unidad_de_Medida__c.field-meta.xml
<CustomField>
    <fullName>Unidad_de_Medida__c</fullName>
    <label>Unidad de Medida</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kilogramos</fullName>
            </value>
            <value>
                <fullName>Libras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HE_Factura_Expo.cls
public class HE_Factura_Expo {
    
    
    public list<Contenido_Envio__c> contenv {get;set;}
    public list<datos> listcontenv {get;set;}
    public string  Name_or   {get;set;}
    public string  TaxID_or  {get;set;}
    public string  ContactName_or   {get;set;}
    public string  Telephone_or  {get;set;}
    public string  E_Mail_or   {get;set;}
    public string  Company_or   {get;set;}
    public string  Country_or   {get;set;}
    public string  Proposito   {get;set;}
    public string  Fecha_Envio   {get;set;}
    public string Breve_Descripcion   {get;set;}
    public string Documento   {get;set;}
    
    public string  Name_des   {get;set;}
    public string  TaxID_des  {get;set;}
    public string  ContactName_des   {get;set;}
    public string  Telephone_des  {get;set;}
    public string  E_Mail_des   {get;set;}
    public string  Company_des   {get;set;}
    public string  Country_des   {get;set;}
    
    
    public decimal  total_packages  {get;set;}
    public decimal  total_unidades   {get;set;}
    public decimal  peso_total  {get;set;}
    public decimal  subtotal   {get;set;}
    public decimal  invoice_total   {get;set;}
    public string  tipo_moneda   {get;set;}
    public string  instruccion_especial   {get;set;}
    
    public string  idp   {get;set;}
    
    
    
    public HE_Factura_Expo(ApexPages.StandardController controller){
        // idp=ApexPages.currentPage().getParameters().get('id');
        idp=controller.getId();
    }
    
    public PageReference  cargar(){
        //  idp='a090v0000043gK4AAI';
        Guias_de_Exportacion__c  gde=[select id,Name,Direccion_Destinatario__c,Contacto__c,Correo_Electronico__c,Telefono_Destinatario__c,Contacto_Destinatario__c,
                                      Ancho__c,Largo__c,Alto__c,Fecha_de_Envio__c,Paquetes__c,Peso_Total__c,Divisa__c,Unidad_de_Medida__c,N_de_Guia__c,
                                      Peso_Agente__c,Contacto__r.name,Contacto__r.email,Telefono__c,Calle__c,Ciudad__c,Pais__c,DDP__c,Otro_Remitente__c,
                                      Shipper_Original__c,ID_Remitente__r.BillingStreet,ID_Remitente__r.BillingCity,ID_Remitente__r.name,ID_Remitente__r.BillingCountry,
                                      Direccion_Destinatario__r.Name ,Proposito_del_Envio__c, Envio_Particular_a_Particular__c, Breve_Descripcion__c, Breve_Descripcion_2__c, Breve_Descripcion_3__c, Breve_Descripcion_4__c,FrxTaxID__c
                                      from Guias_de_Exportacion__c where id=:idp];
        
        Contacto_HotExpress__mdt contacto_hotexpress = [SELECT Name__c, Email__c, Phone__c FROM Contacto_HotExpress__mdt WHERE MasterLabel =: 'ContactoPrincipal' LIMIT 1];
        
        contenv=[SELECT Id, Pickup__c, Descripcion__c, Pais_fab__c,Pais_fab__r.name, Cantidad__c, Unidad_de_Medida__c, Valor_Unitario__c, Condicion_de_Venta__c, Comentarios__c,Codigo_Arancelario__c
                 FROM Contenido_Envio__c WHERE Pickup__c =: gde.id];
        Direcciones__c dir_org;
        if(gde.Otro_Remitente__c!=null){
            dir_org=[SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, 
                     LastActivityDate, Cuenta__c, Direccion__c, Ciudad__c, Estado_Provincia__c,  Pais__r.name,Cod_Pais__c,
                     Codigo_Postal__c, Tipo__c FROM Direcciones__c where id=:gde.Otro_Remitente__c];
        } 
        
        Direcciones__c dir=[SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, 
                            LastActivityDate, Cuenta__c, Direccion__c, Ciudad__c, Estado_Provincia__c,  Pais__r.name,Cod_Pais__c,
                            Codigo_Postal__c, Tipo__c FROM Direcciones__c where id=:gde.Direccion_Destinatario__c];
        Account acc=[SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingCountry, BillingAddress, ShippingAddress,
                     OwnerId, RUT__c, Telefono_2__c, Nombre_Fantasia__c, Haber__c, Debe__c, Saldo__c 
                     FROM Account 
                     WHERE Nombre_Fantasia__c =: 'Hot Express'];
        list<Contact> cont=[SELECT Id, AccountId, Name, MailingAddress, Email,Phone, MobilePhone, OwnerId, Tipo_Cargo__c, Aprobador_Final__c 
                            FROM Contact where AccountId=:acc.id];
        
        if(gde.Shipper_Original__c==true){
            system.debug('1');
            Name_or=gde.ID_Remitente__r.Name;
            TaxID_or =' '+gde.ID_Remitente__c;
            ContactName_or =' '+gde.Contacto__r.name;
            Telephone_or  =' '+gde.Telefono__c;
            E_Mail_or  =' '+gde.Contacto__r.email;
            Company_or   =' '+gde.ID_Remitente__r.BillingStreet;
            Country_or  =' '+gde.ID_Remitente__r.BillingCountry; //acc.BillingCountry; //gde.ID_Remitente__r.BillingCity;
            if(gde.Otro_Remitente__c!=null){
                system.debug('2');
                Name_or=gde.ID_Remitente__r.Name;
                TaxID_or =' '+dir_org.id;
                ContactName_or =' '+gde.Contacto__r.name;
                Telephone_or  =' '+gde.Telefono__c;
                E_Mail_or  =' '+gde.Contacto__r.email;
                Company_or   =' '+dir_org.Direccion__c+', '+dir_org.Ciudad__c+',  '+dir_org.Estado_Provincia__c+' '+dir_org.Codigo_Postal__c ;
                Country_or  =' '+dir_org.Pais__r.name;
                
            }
            else{
                Name_or = (gde.Envio_Particular_a_Particular__c == true ? gde.Contacto__r.name : gde.ID_Remitente__r.Name);
            }
        }else{
            
            system.debug('3');
            Name_or = (gde.Envio_Particular_a_Particular__c == true ? contacto_hotexpress.Name__c : acc.Name);
            TaxID_or ='';
            ContactName_or =' ' + contacto_hotexpress.Name__c;
            Telephone_or  =' ' + contacto_hotexpress.Phone__c;
            E_Mail_or  =' ' + contacto_hotexpress.Email__c;
            Company_or   =' ' + acc.BillingStreet+', '+acc.BillingCity;
            Country_or  =' ' + acc.BillingCountry;
            
            
            
        }
        
        if(gde.Proposito_del_Envio__c=='Muestra sin valor Comercial'){
            Proposito=' Samples without commercial value, not for resale value only for customs purposes';
        }else if(gde.Proposito_del_Envio__c=='Regalo'){
            Proposito=' Unsolicited Gift';
        }else if(gde.Proposito_del_Envio__c=='Regalo a China'){
            Proposito=' Personal Gift';
        }else {
            Proposito=gde.Proposito_del_Envio__c;
        }
        Name_des= (gde.Envio_Particular_a_Particular__c == true ? gde.Contacto_Destinatario__c : gde.Direccion_Destinatario__r.Name);
        TaxID_des = gde.FrxTaxID__c;
        ContactName_des  = gde.Contacto_Destinatario__c;
        Telephone_des =gde.Telefono_Destinatario__c;
        E_Mail_des   =gde.Correo_Electronico__c ;
        Company_des  =dir.Direccion__c+', '+dir.Ciudad__c+', '+dir.Estado_Provincia__c+' '+dir.Codigo_Postal__c ;
        Company_des=Company_des.replace('null', ' ');
        Country_des   =dir.Pais__r.name;
        Fecha_Envio = string.valueOf(gde.Fecha_de_Envio__c);
        Breve_Descripcion = 
                  (gde.Breve_Descripcion__c != null ? gde.Breve_Descripcion__c : '') + ' ' 
                + (gde.Breve_Descripcion_2__c != null ? gde.Breve_Descripcion_2__c + ' ' : '') 
                + (gde.Breve_Descripcion_3__c != null ? gde.Breve_Descripcion_3__c + ' ' : '')
                + (gde.Breve_Descripcion_4__c != null ? gde.Breve_Descripcion_4__c + ' ' : '');
        listcontenv=new list<datos>();
        total_unidades=0;
        subtotal=0;
        for(Contenido_Envio__c ct :contenv){
            datos d=new datos(); 
            d.Packages=1 ;
            d.cantidad=ct.Cantidad__c;
            d.medida='KG';
            d.un_medida=ct.Unidad_de_Medida__c;
            d.descripcion=ct.Descripcion__c;
            d.tarifa = 0;
            d.cod_arancelario = ct.Codigo_Arancelario__c;
            d.pais=ct.Pais_fab__r.name;
            d.valor_unidad=ct.Valor_Unitario__c;
            d.total=ct.Cantidad__c * ct.Valor_Unitario__c;   
            listcontenv.add(d); 
            total_unidades=total_unidades+ct.Cantidad__c;
            subtotal=subtotal+d.total;
        }
        total_packages=gde.Paquetes__c;
        
        peso_total =gde.Peso_Agente__c; 
        
        invoice_total=subtotal;
        tipo_moneda =gde.Divisa__c;         
        
        instruccion_especial = gde.DDP__c ? 'INCOTERM DDP' : '';
        Documento = gde.Name;
        
        return null;
    }
    
    public class datos{
        public integer  Packages  {get;set;}
        public decimal  cantidad   {get;set;}
        public string  medida  {get;set;}
        public string  un_medida   {get;set;}
        public string  descripcion   {get;set;}
        public decimal  tarifa   {get;set;}
        public string  cod_arancelario   {get;set;}
        public string  pais  {get;set;}
        public decimal  valor_unidad    {get;set;}
        public decimal  total  {get;set;} 
    }
}