force-app/main/default/objects/Account/fields/Condicion_Comercial_Global__c.field-meta.xml
<CustomField>
    <fullName>Condicion_Comercial_Global__c</fullName>
    <label>Condición Comercial Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>15 días</fullName>
            </value>
            <value>
                <fullName>30 días</fullName>
            </value>
            <value>
                <fullName>30 días controlado</fullName>
            </value>
            <value>
                <fullName>45 días</fullName>
            </value>
            <value>
                <fullName>60 días</fullName>
            </value>
            <value>
                <fullName>90 días</fullName>
            </value>
            <value>
                <fullName>120 días</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RUT__c.field-meta.xml
<CustomField>
    <fullName>RUT__c</fullName>
    <externalId>true</externalId>
    <label>RUT</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Costo_Solicitud_Pickup__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de Facturar</fullName>
                <default>true</default>
                <label>Pendiente de Facturar</label>
            </value>
            <value>
                <fullName>Facturado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Costo_Solicitud_Pickup__c/fields/Factura__c.field-meta.xml
<CustomField>
    <fullName>Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factura</label>
    <referenceTo>Factura__c</referenceTo>
    <relationshipName>Costos_Solicitudes_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Costo_Solicitud_Pickup__c/fields/Solicitud_de_Pickup__c.field-meta.xml
<CustomField>
    <fullName>Solicitud_de_Pickup__c</fullName>
    <label>Solicitud de Pickup</label>
    <referenceTo>Solicitud_de_Pickup__c</referenceTo>
    <relationshipName>Costos_Solicitudes_Pickup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por Cobrar</fullName>
                <default>true</default>
                <label>Por Cobrar</label>
            </value>
            <value>
                <fullName>Pagada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Anulada NC</fullName>
            </value>
            <value>
                <fullName>Incobrable Otros</fullName>
            </value>
            <value>
                <fullName>Incobrable Dicom</fullName>
            </value>
            <value>
                <fullName>Abonada</fullName>
            </value>
            <value>
                <fullName>Rechazada SII</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/RUT__c.field-meta.xml
<CustomField>
    <fullName>RUT__c</fullName>
    <formula>Cuenta__r.RUT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RUT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HE_PreFactura_Impor.cls
public class HE_PreFactura_Impor {
  public list<Costo_Solicitud_Pickup__c> list_costos{get;set;}
     public Account acc{get;set;}
     list<datosguia> resp {get;set;}
    public list<datosprefactura> prefac {get;set;}
    public decimal totalCLP{get;set;}
     public decimal totalUSD{get;set;}
     
    public string cargar(){
         String id = ApexPages.currentPage().getParameters().get('id');
         String datos = ApexPages.currentPage().getParameters().get('data');
         decimal vd = decimal.valueOf(ApexPages.currentPage().getParameters().get('VD')); 
         system.debug('id'+id);
        system.debug('datos'+datos);
        resp = (list<datosguia>) System.JSON.deserialize(datos, list<datosguia>.class);
        list<string> consulktar_idguias=new list<string>();
        for(datosguia dat:resp){
          consulktar_idguias.add(dat.idguiaconsulta);
        }
        
          system.debug('resp'+resp);
        acc=[select id,name,rut__c,Condicion_Comercial_Global__c,Phone,Billingstreet from Account where id=:id];//'0015A000026wpaN'
        list_costos=[SELECT Id, Name, Valor__c, Solicitud_de_Pickup__c,Solicitud_de_Pickup__r.name, Estado__c, Factura__c FROM Costo_Solicitud_Pickup__c where Solicitud_de_Pickup__c in: consulktar_idguias and Estado__c='Pendiente de Facturar' ];
         totalCLP=0;
         totalUSD=0;
         prefac=new list<datosprefactura>();
        for(Costo_Solicitud_Pickup__c ce:list_costos){
        datosprefactura  df=new  datosprefactura();   
        df.Ngactura=ce.Solicitud_de_Pickup__r.name;
        df.descripcion=ce.name;
        df.montoUSD=ce.Valor__c;
        totalUSD=(totalUSD+df.montoUSD).setScale(0);
        df.montoCLP=(ce.Valor__c * vd).setScale(0);
        totalCLP=(totalCLP+df.montoCLP).setScale(0);
        df.Valordolar=string.valueOf(vd);
       prefac.add(df);

        }
      return null;
    }
    
      public class datosguia{
        public string idguiaconsulta{get;set;}
      }
     public class datosprefactura{
        public string Ngactura{get;set;}
        public string descripcion{get;set;}
        public decimal montoUSD{get;set;}
        public decimal montoCLP{get;set;}
        public string Valordolar{get;set;}
      }
}