force-app/main/default/objects/Account/fields/Nombre_Fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Fantasia__c</fullName>
    <label>Nombre Fantasia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/contrase_a__c.field-meta.xml
<CustomField>
    <fullName>contrase_a__c</fullName>
    <label>Contraseña</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Costo_de_Exportacion__c/fields/Guias_de_Exportacion__c.field-meta.xml
<CustomField>
    <fullName>Guias_de_Exportacion__c</fullName>
    <label>Guías de Exportación</label>
    <referenceTo>Guias_de_Exportacion__c</referenceTo>
    <relationshipName>Costos_Asociados</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Ciudad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Cod_Pais__c.field-meta.xml
<CustomField>
    <fullName>Cod_Pais__c</fullName>
    <formula>Pais__r.Cod_Pais__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cod País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>105</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Estado_Provincia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Provincia__c</fullName>
    <label>Estado/ Provincia</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Zona_Hot__c.field-meta.xml
<CustomField>
    <fullName>Zona_Hot__c</fullName>
    <formula>Text (Pais__r.Zona_Hot__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zona Hot</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Agente__c.field-meta.xml
<CustomField>
    <fullName>Agente__c</fullName>
    <label>Agente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fedex</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Nacional</fullName>
            </value>
            <value>
                <fullName>Hot Express</fullName>
            </value>
            <value>
                <fullName>Proyecto</fullName>
            </value>
            <value>
                <fullName>Servicio Carga</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
            <value>
                <fullName>TNT Nacional</fullName>
            </value>
            <value>
                <fullName>FEDEX IPF</fullName>
            </value>
            <value>
                <fullName>MDZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Alto__c.field-meta.xml
<CustomField>
    <fullName>Alto__c</fullName>
    <label>Alto</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Ancho__c.field-meta.xml
<CustomField>
    <fullName>Ancho__c</fullName>
    <label>Ancho</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <formula>Direccion_Destinatario__r.Ciudad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ciudad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Correo_Electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_Electronico__c</fullName>
    <label>Correo Electrónico</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Embalaje_HOT__c.field-meta.xml
<CustomField>
    <fullName>Embalaje_HOT__c</fullName>
    <label>Embalaje HOT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_Contenido__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Sobre</fullName>
            </value>
            <value>
                <fullName>Pack</fullName>
            </value>
            <value>
                <fullName>Cajas</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Fecha_de_Envio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Envio__c</fullName>
    <label>Fecha de Envío</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Largo__c.field-meta.xml
<CustomField>
    <fullName>Largo__c</fullName>
    <label>Largo</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <formula>Direccion_Destinatario__r.Pais__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Paquetes__c.field-meta.xml
<CustomField>
    <fullName>Paquetes__c</fullName>
    <label>Piezas</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Peso_Agente__c.field-meta.xml
<CustomField>
    <fullName>Peso_Agente__c</fullName>
    <label>Peso Agente</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Peso_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Peso_Cliente__c</fullName>
    <label>Peso Cliente</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Peso_Referencial__c.field-meta.xml
<CustomField>
    <fullName>Peso_Referencial__c</fullName>
    <label>Peso Referencial</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Telefono_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Destinatario__c</fullName>
    <label>Teléfono Destinatario</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Zona_DHL__c.field-meta.xml
<CustomField>
    <fullName>Zona_DHL__c</fullName>
    <formula>text(Direccion_Destinatario__r.Pais__r.Zona_DHL__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zona DHL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Zona_Fedex__c.field-meta.xml
<CustomField>
    <fullName>Zona_Fedex__c</fullName>
    <formula>text(Direccion_Destinatario__r.Pais__r.Zona_Fedex__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zona Fedex</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Zona_HOT__c.field-meta.xml
<CustomField>
    <fullName>Zona_HOT__c</fullName>
    <formula>Text (Direccion_Destinatario__r.Pais__r.Zona_Hot__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zona HOT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Cod_Pais__c.field-meta.xml
<CustomField>
    <fullName>Cod_Pais__c</fullName>
    <label>Cod País</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Nombre_Zonas__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Zonas__c</fullName>
    <label>Nombre Zona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUR AMERICA 1</fullName>
            </value>
            <value>
                <fullName>SUR AMERICA 2</fullName>
            </value>
            <value>
                <fullName>CENTRO Y NORTE AMERICA, CARIBE</fullName>
            </value>
            <value>
                <fullName>EUROPA</fullName>
            </value>
            <value>
                <fullName>ASIA</fullName>
            </value>
            <value>
                <fullName>RESTO DEL MUNDO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Zona_DHL__c.field-meta.xml
<CustomField>
    <fullName>Zona_DHL__c</fullName>
    <label>Zona DHL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Zona 1</fullName>
            </value>
            <value>
                <fullName>Zona 2</fullName>
            </value>
            <value>
                <fullName>Zona 3</fullName>
            </value>
            <value>
                <fullName>Zona 4</fullName>
            </value>
            <value>
                <fullName>Zona 5</fullName>
            </value>
            <value>
                <fullName>Zona 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Zona_Fedex__c.field-meta.xml
<CustomField>
    <fullName>Zona_Fedex__c</fullName>
    <label>Zona Fedex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Zona 1</fullName>
            </value>
            <value>
                <fullName>Zona 2</fullName>
            </value>
            <value>
                <fullName>Zona 3</fullName>
            </value>
            <value>
                <fullName>Zona 4</fullName>
            </value>
            <value>
                <fullName>Zona 5</fullName>
            </value>
            <value>
                <fullName>Zona 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Zona_Hot__c.field-meta.xml
<CustomField>
    <fullName>Zona_Hot__c</fullName>
    <label>Zona Hot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zona 1</fullName>
            </value>
            <value>
                <fullName>Zona 2</fullName>
            </value>
            <value>
                <fullName>Zona 3</fullName>
            </value>
            <value>
                <fullName>Zona 4</fullName>
            </value>
            <value>
                <fullName>Zona 5</fullName>
            </value>
            <value>
                <fullName>Zona 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tarifa_Agente__c/fields/Agente__c.field-meta.xml
<CustomField>
    <fullName>Agente__c</fullName>
    <label>Agente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fedex</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HE_Nuevo_EnvioTEST.cls
@istest(SeeAllData=false)
public class HE_Nuevo_EnvioTEST {
    static testMethod void test1() {
        
        Account  acc=new Account();
        acc.Name='1211';
        insert acc;
        
        Contact  cont=new Contact();
        cont.contrase_a__c='1111';
        cont.Email='test@test.cl';
        cont.AccountId=acc.id;
        cont.LastName='test';
        cont.FirstName='test';
        insert cont;
        
        Account  acc2=new Account();
        acc2.Name='1111111'; 
        acc2.Nombre_Fantasia__c='Hot Express';
        insert acc2;
        
        Pais__c p=new Pais__c();
        p.Name='ARGENTINA';
        p.Cod_Pais__c='AR';
        
        p.Nombre_Zonas__c='SUR AMERICA 1';
        p.Zona_DHL__c='Zona 1';
        p.Zona_Fedex__c='Zona 1';
        p.Zona_Hot__c='Zona 1';
        insert p;
        
        Direcciones__c d=new Direcciones__c();
        d.Name='direccion test';
        d.Cuenta__c=acc.id;
        d.Direccion__c='isidora goyenechea 3000';
        d.Ciudad__c='Buenos Aires';
        d.Estado_Provincia__c='Buenos Aires';
        d.Codigo_Postal__c='7550653';
        d.Pais__c=p.id;
        insert d;
        
        Guias_de_Exportacion__c ge=new Guias_de_Exportacion__c();
        ge.Agente__c='DHL';
        ge.Peso_Referencial__c=8;
        ge.Peso_Cliente__c=8;
        ge.Peso_Agente__c=8;
        ge.Embalaje_HOT__c='cajas'; 
        ge.Telefono_Destinatario__c='+5698765442';
        ge.Correo_Electronico__c='francisca@munoz.com';
        ge.Fecha_de_Envio__c=system.today();
        ge.Paquetes__c=3;
        ge.Largo__c=2;
        ge.Ancho__c=2;
        ge.Alto__c=2;
        ge.Peso_Total__c=8;
        ge.Unidad_de_Medida__c='kilogramo';
        ge.Divisa__c='USD - U.S. Dollar';
        ge.Proposito_del_Envio__c='Efectos Personales';
        ge.Tipo_Contenido__c='Mercancías';
        ge.Direccion_Destinatario__c=d.id;
        ge.Contacto_Destinatario__c='contacto test';
        ge.ID_Remitente__c=acc.id;
        ge.Validado_por_Area_de_Finanzas__c=true;
        /*   ge.Contacto__c,
ge.Tarifa_Cliente__c,
ge.Calle__c,
ge.Ciudad__c,
ge.Cod_Postal__c,
ge.Pais__c,
ge.Valor_Combustible__c,
ge.Estado__c,
ge.Tarifa_Agente__c,
ge.Valor_Agente__c*/
        insert ge;
        Contenido_Envio__c  con=new Contenido_Envio__c();
        con.Pickup__c=ge.id;
        con.Descripcion__c='vino';
        con.Pais_fab__c=p.id;
        con.Cantidad__c=1;
        con.Unidad_de_Medida__c='Unidades';
        con.Valor_Unitario__c=15;
        insert con;
        
        Costo__c c=new Costo__c();
        c.Name='comvustible';
        insert c;
        
        Costo_de_Exportacion__c cosex=new Costo_de_Exportacion__c();
        cosex.Costo__c=c.id;
        cosex.Valor__c=8;
        cosex.Guias_de_Exportacion__c=ge.Id;
        cosex.Estado__c= 'Pendiente de Facturar';
        insert cosex;
        string us=UserInfo.getUserId();
         string datog='{"remitente":"0015A000026wpWEQAY","idp":"0030v00000QLrOtAAL","OwnerId":"'+us+'","iddir_retiro":"a0J0v000002L0t5EAC","idcontacto":"0030v00000O1yzPAAR","iddireccion":"a0J0v000002L10AEAS","Nombre":"casa rancagua","direccion":"el bosque 123","tipo_contenido":"Mercancias","Proposito_envio":"Efectos PersonalesDeshacer","ciudad":"rancagua","Estado_Provincia":"rancagus","codigo_Postal":"123434","Pais":"CHILE","contacto":"1qweq","email":"ydsasa@mal.nr","telefono":"12123","productos":[{"id":"0","code":"0","Descripcion":"test","pais_Fabricacion":"a0M0v000003pk5jEAA","Cantidad":"1","Unidad_Medida":"Unidades","Valor_Unitario":"1"}],"alto":"1","ancho":"1","largo":"1","peso":"1","DDP":"NO","Embalaje":"Cajas","attachmentName":"tabstrip.html","N_paquete":"1"}';
        string datosd='{"nombre":"casa test","Ciudad":"test","codigo_Postal":"1241","Direccion":"test","Estado_Provincia":"test","Pais":"'+p.id+'","id":"'+acc.id+'","OwnerId":"'+us+'"}';
        string datosc='{"Idcuenta":"'+acc.id+'","Nombre": "test","Apellidos":"test","Correo":"test@test.cl","Telefono": "12344","Tipo_Cargo": "Otro"}';
        apexPages.Currentpage().getParameters().put('idp',cont.id);
        apexPages.Currentpage().getParameters().put('idc',acc.id);
        apexPages.Currentpage().getParameters().put('datos',datosd);
        HE_Nuevo_Envio  he=new   HE_Nuevo_Envio();
        he.datos();
        he.guardadirecion();
        apexPages.Currentpage().getParameters().put('datos',datosc);
        
        he.guardadrcontacto();
        
       // he.guardaGuia();
        
       
    
    }
    
     static testMethod void test2() {
        
        Account  acc=new Account();
        acc.Name='1211';
        insert acc;
        
        Contact  cont=new Contact();
        cont.contrase_a__c='1111';
        cont.Email='test@test.cl';
        cont.AccountId=acc.id;
        cont.LastName='test';
        cont.FirstName='test';
        insert cont;
        
        Account  acc2=new Account();
        acc2.Name='1111111'; 
        acc2.Nombre_Fantasia__c='Hot Express';
        insert acc2;
        
        Pais__c p=new Pais__c();
        p.Name='ARGENTINA';
        p.Cod_Pais__c='AR';
        
        p.Nombre_Zonas__c='SUR AMERICA 1';
        p.Zona_DHL__c='Zona 1';
        p.Zona_Fedex__c='Zona 1';
        p.Zona_Hot__c='Zona 1';
        insert p;
        
        Direcciones__c d=new Direcciones__c();
        d.Name='direccion test';
        d.Cuenta__c=acc.id;
        d.Direccion__c='isidora goyenechea 3000';
        d.Ciudad__c='Buenos Aires';
        d.Estado_Provincia__c='Buenos Aires';
        d.Codigo_Postal__c='7550653';
        d.Pais__c=p.id;
        insert d;
        
        Guias_de_Exportacion__c ge=new Guias_de_Exportacion__c();
        ge.Agente__c='DHL';
        ge.Peso_Referencial__c=8;
        ge.Peso_Cliente__c=8;
        ge.Peso_Agente__c=8;
        ge.Embalaje_HOT__c='cajas'; 
        ge.Telefono_Destinatario__c='+5698765442';
        ge.Correo_Electronico__c='francisca@munoz.com';
        ge.Fecha_de_Envio__c=system.today();
        ge.Paquetes__c=3;
        ge.Largo__c=2;
        ge.Ancho__c=2;
        ge.Alto__c=2;
        ge.Peso_Total__c=8;
        ge.Unidad_de_Medida__c='kilogramo';
        ge.Divisa__c='USD - U.S. Dollar';
        ge.Proposito_del_Envio__c='Efectos Personales';
        ge.Tipo_Contenido__c='Mercancías';
        ge.Direccion_Destinatario__c=d.id;
        ge.Contacto_Destinatario__c='contacto test';
        ge.ID_Remitente__c=acc.id;
        ge.Validado_por_Area_de_Finanzas__c=true;
        /*   ge.Contacto__c,
ge.Tarifa_Cliente__c,
ge.Calle__c,
ge.Ciudad__c,
ge.Cod_Postal__c,
ge.Pais__c,
ge.Valor_Combustible__c,
ge.Estado__c,
ge.Tarifa_Agente__c,
ge.Valor_Agente__c*/
        insert ge;
        Contenido_Envio__c  con=new Contenido_Envio__c();
        con.Pickup__c=ge.id;
        con.Descripcion__c='vino';
        con.Pais_fab__c=p.id;
        con.Cantidad__c=1;
        con.Unidad_de_Medida__c='Unidades';
        con.Valor_Unitario__c=15;
        insert con;
        
        Costo__c c=new Costo__c();
        c.Name='comvustible';
        insert c;
        
        Costo_de_Exportacion__c cosex=new Costo_de_Exportacion__c();
        cosex.Costo__c=c.id;
        cosex.Valor__c=8;
        cosex.Guias_de_Exportacion__c=ge.Id;
        cosex.Estado__c= 'Pendiente de Facturar';
        insert cosex;
        string us=UserInfo.getUserId();
         string datog='{"remitente":"'+acc.id+'","idp":"'+cont.id+'","OwnerId":"'+us+'","iddir_retiro":"'+d.id+'","idcontacto":"'+cont.id+'","iddireccion":"'+d.id+'","Nombre":"casa rancagua","direccion":"el bosque 123","tipo_contenido":"Mercancias","Proposito_envio":"Efectos PersonalesDeshacer","ciudad":"rancagua","Estado_Provincia":"rancagus","codigo_Postal":"123434","Pais":"CHILE","contacto":"1qweq","email":"ydsasa@mal.nr","telefono":"12123","productos":[{"id":"0","code":"0","Descripcion":"test","pais_Fabricacion":"'+p.id+'","Cantidad":"1","Unidad_Medida":"Unidades","Valor_Unitario":"1"}],"alto":"1","ancho":"1","largo":"1","peso":"1","DDP":"NO","Embalaje":"Cajas","attachmentName":"tabstrip.html","N_paquete":"1"}';
        string datosd='{"nombre":"casa test","Ciudad":"test","codigo_Postal":"1241","Direccion":"test","Estado_Provincia":"test","Pais":"'+p.id+'","id":"'+acc.id+'","OwnerId":"'+us+'"}';
        apexPages.Currentpage().getParameters().put('idp',cont.id);
        apexPages.Currentpage().getParameters().put('idc',acc.id);
        apexPages.Currentpage().getParameters().put('datos',datog);
        HE_Nuevo_Envio  he=new   HE_Nuevo_Envio();
        he.datos();
          he.guardaGuia();
        
       
    
    }
}