force-app/main/default/objects/Account/fields/RUT__c.field-meta.xml
<CustomField>
    <fullName>RUT__c</fullName>
    <externalId>true</externalId>
    <label>RUT</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ID_Remitente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guías de Exportación</relationshipLabel>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/ID_Remitente__c.field-meta.xml
<CustomField>
    <fullName>ID_Remitente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID Remitente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <formula>Direccion_Destinatario__r.Pais__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Total_Costos_sin_Facturar__c.field-meta.xml
<CustomField>
    <fullName>Total_Costos_sin_Facturar__c</fullName>
    <label>Total Costos sin Facturar</label>
    <summarizedField>Costo_de_Exportacion__c.Valor__c</summarizedField>
    <summaryFilterItems>
        <field>Costo_de_Exportacion__c.Estado__c</field>
        <operation>equals</operation>
        <value>Pendiente de Facturar</value>
    </summaryFilterItems>
    <summaryForeignKey>Costo_de_Exportacion__c.Guias_de_Exportacion__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Zona_HOT__c.field-meta.xml
<CustomField>
    <fullName>Zona_HOT__c</fullName>
    <formula>Text (Direccion_Destinatario__r.Pais__r.Zona_Hot__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zona HOT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Zona_Hot__c.field-meta.xml
<CustomField>
    <fullName>Zona_Hot__c</fullName>
    <label>Zona Hot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zona 1</fullName>
            </value>
            <value>
                <fullName>Zona 2</fullName>
            </value>
            <value>
                <fullName>Zona 3</fullName>
            </value>
            <value>
                <fullName>Zona 4</fullName>
            </value>
            <value>
                <fullName>Zona 5</fullName>
            </value>
            <value>
                <fullName>Zona 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HE_Consulta_Clientes_Facturar.cls
public class HE_Consulta_Clientes_Facturar {
    public   list<Account> Acc{get;set;}
    public   list<Contact> con{get;set;}
    public   string rut{get;set;}
    public   string resultJSON{get;set;}
    
    
    public HE_Consulta_Clientes_Facturar(){
        
    }
    public PageReference Obtenerclientes(){
        
        
        list<Guias_de_Exportacion__c> ge= [SELECT ID_Remitente__c
                                           FROM Guias_de_Exportacion__c 
                                           where Total_Costos_sin_Facturar__c > 0];
        list<string>  listidacc=new list<string>();
        list<string>  listidcont=new list<string>();
        id d;
        for(Guias_de_Exportacion__c g:ge){
            if(d!=g.ID_Remitente__c){
                listidacc.add(g.ID_Remitente__c);
                d=g.ID_Remitente__c;
            }
        }
        ge= [SELECT Contacto__c
             FROM Guias_de_Exportacion__c 
             where Total_Costos_sin_Facturar__c > 0];
        for(Guias_de_Exportacion__c g:ge){
            if(d!=g.Contacto__c){
                listidcont.add(g.Contacto__c);
                d=g.Contacto__c;
            }
        }  
        
        
        Acc=[select  id, name from Account  where id in: listidacc order by name];
        Con=[SELECT Id,  Name FROM Contact where  id in: listidcont order by name];
        system.debug('Acc'+Acc);
        return null;    
    }
    
    
    
    public string consultar_rut(){
        String datos = ApexPages.currentPage().getParameters().get('tipo');
        String rut = ApexPages.currentPage().getParameters().get('rut');
        system.debug('rut'+rut);
        
        
        system.debug('datos'+datos);
        list<Guias_de_Exportacion__c> ge;
        if(datos!=''){
            ge= [SELECT Contacto__c,Contacto__r.name,pais__c,Zona_HOT__c
                 FROM Guias_de_Exportacion__c 
                 where Total_Costos_sin_Facturar__c > 0 and ID_Remitente__c=:datos order by Contacto__c];
            
        }else{
            ge= [SELECT Contacto__c,Contacto__r.name,pais__c,Zona_HOT__c 
                 FROM Guias_de_Exportacion__c 
                 where Total_Costos_sin_Facturar__c > 0 and ID_Remitente__r.RUT__c=:rut order by Contacto__c];
            
        }
        list <contacto> conlist=new list <contacto>();
        id idcom;
        for(Guias_de_Exportacion__c  g:ge){
            if(idcom!=g.Contacto__c){
                contacto con=new contacto();
                con.id=g.Contacto__c;
                con.nombre=g.Contacto__r.name; 
                conlist.add(con);
                idcom=g.Contacto__c;
            }
        }
        
        list <pais> paislist=new list <pais>();
        string paiscom;
        for(Guias_de_Exportacion__c  g:ge){
            if(paiscom!=g.pais__c){
                pais ps=new pais();
                ps.pais=g.pais__c;
                ps.zona=g.Zona_HOT__c;
                paislist.add(ps);
                paiscom=g.pais__c;
            }
        }
        respuesta res=new respuesta();
        res.contacto=conlist;
        res.pais=paislist;
        
        resultJSON=json.serialize(res);
        
        
        return null;
    }
    
    public class respuesta{
        public   list<contacto> contacto{get;set;}
        public   list<pais> pais{get;set;}
        
    }
    
    public class contacto{
        public string id{get;set;} 
        public string nombre{get;set;} 
    }
    
    public class pais{
        public string pais{get;set;} 
        public string zona{get;set;} 
        
    }
    
    
}