force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Ciudad_Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Ciudad_Consignatario__c</fullName>
    <label>Ciudad Consignatario</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Cod_Postal_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Cod_Postal_Vendedor__c</fullName>
    <label>Cod Postal Vendedor</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Consignatario__c</fullName>
    <label>Consignatario</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Consignee_Phone__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Phone__c</fullName>
    <label>Consignee Phone</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Direccion_Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Consignatario__c</fullName>
    <label>Dirección Consignatario</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Pais_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Pais_Vendedor__c</fullName>
    <label>País Vendedor</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Pieces__c.field-meta.xml
<CustomField>
    <fullName>Pieces__c</fullName>
    <label>Pieces</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Shipper_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Address__c</fullName>
    <label>Shipper Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Shipper_Town__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Town__c</fullName>
    <label>Shipper Town</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Guias_Importacion__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PDFconstructor_Importacion.cls
public class PDFconstructor_Importacion {
  public Detalles_Guias_Importacion__c detmas {get;set;}
    public string Iddet {get;set;}
    public string fecha {get;set;}
  public PDFconstructor_Importacion(ApexPages.StandardController controller){
        
        Iddet = ApexPages.currentPage().getParameters().get('id');
     // Iddet ='a050v000002xa5VAAQ';
      system.debug('Iddet'+Iddet);
      detmas=[SELECT Id,Vendedor__c,Shipper_Address__c,Shipper_Town__c,Cod_Postal_Vendedor__c,Pais_Vendedor__c,
              Consignatario__c,Direccion_Consignatario__c,Comuna__c,Ciudad_Consignatario__c,Postal_Code__c,Consignee_Phone__c,
              Pieces__c,Descripcion__c,Valor__c FROM Detalles_Guias_Importacion__c where id=:Iddet];
      system.debug('detmas'+detmas);
      date fch=date.today();
      fecha=fch.format();
  }
    
    public PageReference  inicio(){
        return null;
    }
}