force-app/main/default/objects/Detalles_Master__c/fields/Bag_Code__c.field-meta.xml
<CustomField>
    <fullName>Bag_Code__c</fullName>
    <label>Bag Code</label>
    <referenceTo>Caja__c</referenceTo>
    <relationshipLabel>Detalles Guías</relationshipLabel>
    <relationshipName>Detalles_Gu_as</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Comuna__c.field-meta.xml
<CustomField>
    <fullName>Comuna__c</fullName>
    <description>Ciudad destinatario</description>
    <label>Comuna</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Consignatario__c</fullName>
    <description>Nombre destinatario</description>
    <label>Consignatario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/DIP_Confecionada__c.field-meta.xml
<CustomField>
    <fullName>DIP_Confecionada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DIP Confecionada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Direccion_Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Consignatario__c</fullName>
    <description>Dirección destinatario</description>
    <label>Dirección Consignatario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Direccion_Normalizada__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Normalizada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direccion_Normalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Enviado_a_Correo__c.field-meta.xml
<CustomField>
    <fullName>Enviado_a_Correo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado a Correo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Estado_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Estado_Cliente__c</fullName>
    <label>Estado Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Recepcionado en Chile</fullName>
            </value>
            <value>
                <fullName>En proceso Aduana</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
            <value>
                <fullName>En Tránsito a Centro de Distribución</fullName>
            </value>
            <value>
                <fullName>Entregado a Correos de Chile</fullName>
            </value>
            <value>
                <fullName>Entregado a Blue Express</fullName>
            </value>
            <value>
                <fullName>Entregado a Chilexpress</fullName>
            </value>
            <value>
                <fullName>Parcel arrived at terminal warehouse at destination country</fullName>
            </value>
            <value>
                <fullName>Parcel completed Customs Clearance at destination country</fullName>
            </value>
            <value>
                <fullName>Entregado a Starken</fullName>
            </value>
            <value>
                <fullName>Entregado a Chazki</fullName>
            </value>
            <value>
                <fullName>Entregado a WSP</fullName>
            </value>
            <value>
                <fullName>In processing of customs clearance formalities</fullName>
            </value>
            <value>
                <fullName>Documentation classified at Customs</fullName>
            </value>
            <value>
                <fullName>Parcel transferred to last mile operator CXP</fullName>
            </value>
            <value>
                <fullName>Parcel transferred to last mile operator WSP</fullName>
            </value>
            <value>
                <fullName>Parcel transferred to last mile operator STK</fullName>
            </value>
            <value>
                <fullName>Parcel transferred to last mile operator Easy</fullName>
            </value>
            <value>
                <fullName>Entregado a operador de última milla</fullName>
            </value>
            <value>
                <fullName>En centro de distribución para reparto</fullName>
            </value>
            <value>
                <fullName>En reparto</fullName>
            </value>
            <value>
                <fullName>Entregado a cliente final</fullName>
            </value>
            <value>
                <fullName>Cliente no estaba en dirección</fullName>
            </value>
            <value>
                <fullName>Recepcionado en central HOT Express</fullName>
            </value>
            <value>
                <fullName>Entregado a Fedex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Flete__c.field-meta.xml
<CustomField>
    <fullName>Flete__c</fullName>
    <label>Flete</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <label>Master</label>
    <referenceTo>Master__c</referenceTo>
    <relationshipName>Detalles_Manifiestos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <label>Peso</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Pieces__c.field-meta.xml
<CustomField>
    <fullName>Pieces__c</fullName>
    <description>Número de paquetes del registro</description>
    <label>Pieces</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Rut_Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Rut_Consignatario__c</fullName>
    <label>Rut Consignatario</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Seguro__c.field-meta.xml
<CustomField>
    <fullName>Seguro__c</fullName>
    <label>Seguro</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Aeropuerto_Origen__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto_Origen__c</fullName>
    <label>Aeropuerto Origen</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Fecha_Manifiesto_Aduana__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Manifiesto_Aduana__c</fullName>
    <label>Fecha Manifiesto Aduana</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Master_AirwayBill__c.field-meta.xml
<CustomField>
    <fullName>Master_AirwayBill__c</fullName>
    <externalId>true</externalId>
    <label>Master AirwayBill</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/N_Manifiesto_Aduana__c.field-meta.xml
<CustomField>
    <fullName>N_Manifiesto_Aduana__c</fullName>
    <description>Número entregado por la aduana</description>
    <inlineHelpText>Número entregado por la aduana</inlineHelpText>
    <label>Nº Manifiesto Aduana</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/N_Vuelo__c.field-meta.xml
<CustomField>
    <fullName>N_Vuelo__c</fullName>
    <label>Nº Vuelo</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HE_Guia_Aerea.cls
public class HE_Guia_Aerea {
    public  Detalles_Master__c  dm{get;set;}
    // public  string   fecha{get;set;}
    public  date fecha{get;set;}
    public String fechaFormateada { get; set; }
    public string idDetMasT {get;set;}
       public HE_Guia_Aerea(ApexPages.StandardController controller){
      idDetMasT=controller.getId(); 
    }
    public string cargar(){
        dm=[SELECT Id, Name, Master__c,Master__r.Master_AirwayBill__c,Master__r.N_Manifiesto_Aduana__c,
            Master__r.Fecha_Manifiesto_Aduana__c,Master__r.Aeropuerto_Origen__c,Master__r.N_Vuelo__c, Vendedor__c,
            Consignatario__c, Direccion_Consignatario__c, Comuna__c, Pieces__c, Peso__c,
            Valor__c, Descripcion__c, Rut_Consignatario__c, Enviado_a_Correo__c, 
            Bag_Code__c, DIP_Confecionada__c, Estado_Cliente__c, Seguro__c, Flete__c, Direccion_Normalizada__c 
            FROM Detalles_Master__c 
            WHERE Id =: idDetMasT];
        fecha=null;
        fechaFormateada = null;
        if(dm.Master__r.Fecha_Manifiesto_Aduana__c!=null){
            //datetime  fechahora= dm.Master__r.Fecha_Manifiesto_Aduana__c;
            // fecha=  fechahora.format('dd/MM/YYYY');
            fecha = dm.Master__r.Fecha_Manifiesto_Aduana__c;
            String dia = String.valueOf(fecha.day());
            String mes = String.valueOf(fecha.month());
            String ano = String.valueOf(fecha.year());

            // Agrega un "0" antes si el día o el mes tienen un solo dígito
            if (dia.length() == 1) {
                dia = '0' + dia;
            }
            if (mes.length() == 1) {
                mes = '0' + mes;
            }

            fechaFormateada = dia + '/' + mes + '/' + ano;
        }
        return null;
    }
}