force-app/main/default/objects/Detalles_Master__c/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <label>Client Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Comuna__c.field-meta.xml
<CustomField>
    <fullName>Comuna__c</fullName>
    <description>Ciudad destinatario</description>
    <label>Comuna</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Consignatario__c</fullName>
    <description>Nombre destinatario</description>
    <label>Consignatario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Consignee_Phone__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Phone__c</fullName>
    <description>Teléfono destinatario</description>
    <label>Consignee Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Destination_Generic_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Destination_Generic_Postal_Code__c</fullName>
    <label>Destination Generic Postal Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Direccion_Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Consignatario__c</fullName>
    <description>Dirección destinatario</description>
    <label>Dirección Consignatario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Direccion_Normalizada__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Normalizada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direccion_Normalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Estado_Guia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Guia__c</fullName>
    <label>Estado Guía</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documental</fullName>
            </value>
            <value>
                <fullName>Menor a 30</fullName>
            </value>
            <value>
                <fullName>Facturada</fullName>
            </value>
            <value>
                <fullName>Abandonado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Retenido por RUT</fullName>
            </value>
            <value>
                <fullName>Retenido por Aduana</fullName>
            </value>
            <value>
                <fullName>Retenido por Visación</fullName>
            </value>
            <value>
                <fullName>Retenido en escaner</fullName>
            </value>
            <value>
                <fullName>En cadena de custodia</fullName>
            </value>
            <value>
                <fullName>Paquete No Recibido</fullName>
            </value>
            <value>
                <fullName>Retenido por error ISP</fullName>
            </value>
            <value>
                <fullName>Retenido por peso</fullName>
            </value>
            <value>
                <fullName>Sobrante</fullName>
            </value>
            <value>
                <fullName>Alto valor</fullName>
            </value>
            <value>
                <fullName>RUT no conseguido Retenido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Factor_Peso__c.field-meta.xml
<CustomField>
    <fullName>Factor_Peso__c</fullName>
    <label>Factor Peso</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Factor_Pieces__c.field-meta.xml
<CustomField>
    <fullName>Factor_Pieces__c</fullName>
    <label>Factor Pieces</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/HD_PUDO__c.field-meta.xml
<CustomField>
    <fullName>HD_PUDO__c</fullName>
    <label>HD-PUDO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HD</fullName>
            </value>
            <value>
                <fullName>PUDO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <label>Master</label>
    <referenceTo>Master__c</referenceTo>
    <relationshipName>Detalles_Manifiestos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Nombre_Cod_Arancelario__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Cod_Arancelario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre Cod Arancelario</label>
    <referenceTo>Codigo_Arancelario__c</referenceTo>
    <relationshipLabel>Detalles Guías</relationshipLabel>
    <relationshipName>Detalles_Manifiestos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <label>Peso</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Pieces__c.field-meta.xml
<CustomField>
    <fullName>Pieces__c</fullName>
    <description>Número de paquetes del registro</description>
    <label>Pieces</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Código postal destinatario</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Postal_Services__c.field-meta.xml
<CustomField>
    <fullName>Postal_Services__c</fullName>
    <label>Postal Services</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Puerto_de_Destino__c.field-meta.xml
<CustomField>
    <fullName>Puerto_de_Destino__c</fullName>
    <label>Puerto de Destino</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Rut_Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Rut_Consignatario__c</fullName>
    <label>Rut Consignatario</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Shipper_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Address__c</fullName>
    <label>Shipper Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Shipper_Town__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Town__c</fullName>
    <label>Shipper Town</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Type_of_Mail__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Mail__c</fullName>
    <label>Type of Mail</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registrado</fullName>
            </value>
            <value>
                <fullName>No Registrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Undelivered_Parcels__c.field-meta.xml
<CustomField>
    <fullName>Undelivered_Parcels__c</fullName>
    <label>Undelivered Parcels</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndPoint__mdt/fields/Codigo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Cliente__c</fullName>
    <label>Codigo Cliente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndPoint__mdt/fields/contrase_a__c.field-meta.xml
<CustomField>
    <fullName>contrase_a__c</fullName>
    <label>contraseña</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndPoint__mdt/fields/usuario__c.field-meta.xml
<CustomField>
    <fullName>usuario__c</fullName>
    <label>usuario</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Aeropuerto_Destino__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto_Destino__c</fullName>
    <label>Aeropuerto Destino</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Aeropuerto_Origen__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto_Origen__c</fullName>
    <label>Aeropuerto Origen</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Masters</relationshipLabel>
    <relationshipName>Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Recepcionado</fullName>
                <default>true</default>
                <label>Recepcionado</label>
            </value>
            <value>
                <fullName>En Digitación</fullName>
            </value>
            <value>
                <fullName>Enviado a Atrex</fullName>
            </value>
            <value>
                <fullName>Depurado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master__c/fields/Fecha_Recepcion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Recepcion__c</fullName>
    <label>Fecha Recepción</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Fecha_Vuelo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Vuelo__c</fullName>
    <label>Fecha Vuelo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Master_AirwayBill__c.field-meta.xml
<CustomField>
    <fullName>Master_AirwayBill__c</fullName>
    <externalId>true</externalId>
    <label>Master AirwayBill</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/N_Manifiesto_Aduana__c.field-meta.xml
<CustomField>
    <fullName>N_Manifiesto_Aduana__c</fullName>
    <description>Número entregado por la aduana</description>
    <inlineHelpText>Número entregado por la aduana</inlineHelpText>
    <label>Nº Manifiesto Aduana</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/N_Vuelo__c.field-meta.xml
<CustomField>
    <fullName>N_Vuelo__c</fullName>
    <label>Nº Vuelo</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Total_Cajas__c.field-meta.xml
<CustomField>
    <fullName>Total_Cajas__c</fullName>
    <label>Total Cajas</label>
    <summaryForeignKey>Caja__c.Master__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Total_Peso__c.field-meta.xml
<CustomField>
    <fullName>Total_Peso__c</fullName>
    <label>Total Peso</label>
    <summarizedField>Detalles_Master__c.Peso__c</summarizedField>
    <summaryForeignKey>Detalles_Master__c.Master__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Total_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_Piezas__c</fullName>
    <label>Total Piezas</label>
    <summarizedField>Detalles_Master__c.Pieces__c</summarizedField>
    <summaryForeignKey>Detalles_Master__c.Master__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Total_Valor__c.field-meta.xml
<CustomField>
    <fullName>Total_Valor__c</fullName>
    <label>Total Valor</label>
    <summarizedField>Detalles_Master__c.Valor__c</summarizedField>
    <summaryForeignKey>Detalles_Master__c.Master__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/HE_AdmicionCEP_envia_a_correos.cls
public class HE_AdmicionCEP_envia_a_correos {
    public string idmaster {get;set;}
    public string inicio {get;set;}
    public string fin {get;set;}
    public string totalenvios {get;set;}
    public  HE_AdmicionCEP_envia_a_correos(ApexPages.StandardController  Controller) {
        idmaster=ApexPages.currentPage().getParameters().get('id');
        inicio=ApexPages.currentPage().getParameters().get('in');
        fin=ApexPages.currentPage().getParameters().get('fn'); 
       // idmaster='a040v000002SChh';
        system.debug('idmaster'+idmaster);
        system.debug('inicio'+inicio);
        system.debug('fin'+fin);
        if(inicio==null){
            system.debug('entro por aca');
            inicio='0';  
        }
        if(fin==null){
            system.debug('entro por aca 2');
            fin='50';        
        }
        system.debug('idmaster'+idmaster);
        system.debug('inicio'+inicio);
        system.debug('fin'+fin);
        
    }
    public PageReference enviar_a_correos(){
        integer contador =0;
        system.debug('entro a normalizacion');
        system.debug('inicio'+inicio);
        system.debug('fin'+fin);
        EndPoint__mdt ep=[SELECT Id, usuario__c, contrase_a__c, Codigo_Cliente__c, Label FROM EndPoint__mdt where Label='normalizacion' limit 1 ];
        
        Master__c   mt=[select Id, Name, Fecha_Recepcion__c, Estado__c, N_Manifiesto_Aduana__c, Cuenta__c, Total_Valor__c, Total_Peso__c, Total_Piezas__c,
                        Aeropuerto_Origen__c, Aeropuerto_Destino__c, N_Vuelo__c, Total_Cajas__c, Master_AirwayBill__c, Fecha_Vuelo__c
                        from Master__c  where id=:idmaster];
        
        list<Detalles_Master__c> detmast=[select Id, Name, Master__c, Order_Number__c, Type_of_Mail__c, Vendedor__c, Shipper_Address__c, Shipper_Town__c, Consignatario__c, 
                                          Direccion_Consignatario__c, Comuna__c, Postal_Code__c, Consignee_Phone__c, Pieces__c, Peso__c, Valor__c, Puerto_de_Destino__c,Rut_Consignatario__c,
                                          Destination_Generic_Postal_Code__c, Client_Code__c, HD_PUDO__c, Undelivered_Parcels__c, Postal_Services__c, Descripcion__c,Direccion_Normalizada__c,
                                          Nombre_Cod_Arancelario__c, Estado_Guia__c, Cod_Arancelario__c, Factor_Peso__c, Factor_Pieces__c, Tarifa_Guia__c, Bag_Code__c ,Consignee_Email__c
                                          FROM Detalles_Master__c WHERE Master__c=:idmaster and Direccion_Normalizada__c=true order  by id];
        string  usuario =ep.usuario__c;
        string contrasena =ep.contrase_a__c;
        // string contrasena ='b9d591ae8ef9d36bb7d4';
        string id='1';
        
        system.debug('detmast'+detmast.size());  
        
        for(integer i=integer.valueOf(inicio);i<integer.valueOf(fin);i++){
            if(detmast.get(i).Direccion_Normalizada__c==true){
                admicionCEP.AdmisionTO admisionTo =new admicionCEP.AdmisionTO();
                
                admisionTo.CodigoAdmision=detmast.get(i).name;
                admisionTo.ClienteRemitente=ep.Codigo_Cliente__c;
                admisionTo.CentroRemitente='';
                admisionTo.NombreRemitente=detmast.get(i).Vendedor__c;
                admisionTo.DireccionRemitente=detmast.get(i).Shipper_Address__c;
                admisionTo.PaisRemitente='056';
                admisionTo.CodigoPostalRemitente='';
                admisionTo.ComunaRemitente=detmast.get(i).Shipper_Town__c;
                admisionTo.RutRemitente='';
                admisionTo.PersonaContactoRemitente=detmast.get(i).Vendedor__c;
                admisionTo.TelefonoContactoRemitente='0';
                admisionTo.ClienteDestinatario='';
                admisionTo.CentroDestinatario='';
                admisionTo.NombreDestinatario=detmast.get(i).Consignatario__c;
                admisionTo.DireccionDestinatario=detmast.get(i).Direccion_Consignatario__c;
                admisionTo.PaisDestinatario='056';
                admisionTo.CodigoPostalDestinatario=detmast.get(i).Postal_Code__c;
                admisionTo.ComunaDestinatario=detmast.get(i).Comuna__c;
                admisionTo.RutDestinatario=detmast.get(i).Rut_Consignatario__c;
                admisionTo.PersonaContactoDestinatario=detmast.get(i).Consignatario__c;
                admisionTo.TelefonoContactoDestinatario=detmast.get(i).Consignee_Phone__c;
                admisionTo.CodigoServicio='24';
                admisionTo.NumeroTotalPiezas=integer.valueOf(detmast.get(i).Pieces__c);
                admisionTo.Kilos=detmast.get(i).Peso__c;
                admisionTo.Volumen=0;
                admisionTo.NumeroReferencia=detmast.get(i).name;
                admisionTo.ImporteReembolso=0;
                admisionTo.ImporteValorDeclarado=0;
                admisionTo.TipoPortes='p';
                admisionTo.Observaciones='';
                admisionTo.Observaciones2='';
                admisionTo.EmailDestino=detmast.get(i).Consignee_Email__c;
                admisionTo.TipoMercancia=detmast.get(i).Descripcion__c;
                admisionTo.DevolucionConforme='N';
                admisionTo.NumeroDocumentos=0;
                admisionTo.PagoSeguro='N';
                admicionCEP.ServicioExternoAdmisionCEPSoap   lisadm =new   admicionCEP.ServicioExternoAdmisionCEPSoap();
                admicionCEP.RespuestaAdmisionTO   lisresp =new   admicionCEP.RespuestaAdmisionTO();
                
                try{
                    system.debug('admisionTo=='+admisionTo);
                    if(!test.isRunningTest()){
                         lisresp=lisadm.admitirEnvio( usuario, contrasena, admisionTo);
                    }else{
                        lisresp.NumeroEnvio=detmast.get(i).name;
                    }
                    
                    system.debug('CodigoSucursal=='+lisresp.CodigoSucursal);
                    system.debug('NombreSucursal=='+lisresp.NombreSucursal);
                    system.debug('Cuartel=='+lisresp.Cuartel);
                    system.debug('Sector=='+lisresp.Sector);
                    system.debug('SDP=='+lisresp.SDP);
                    system.debug('Movil=='+lisresp.Movil);
                    system.debug('AbreviaturaCentro=='+lisresp.AbreviaturaCentro);
                    system.debug('CodigoDelegacionDestino=='+lisresp.CodigoDelegacionDestino);
                    system.debug('NombreDelegacionDestino=='+lisresp.NombreDelegacionDestino);
                    system.debug('DireccionDestino=='+lisresp.DireccionDestino);
                    system.debug('CodigoEncaminamiento=='+lisresp.CodigoEncaminamiento);
                    system.debug('GrabarEnvio=='+lisresp.GrabarEnvio);
                    system.debug('NumeroEnvio=='+lisresp.NumeroEnvio);
                    system.debug('ComunaDestino=='+lisresp.ComunaDestino);
                    system.debug('AbreviaturaServicio=='+lisresp.AbreviaturaServicio);
                    system.debug('IdTransaccional=='+lisresp.IdTransaccional);
                    system.debug('CodigoAdmision=='+lisresp.CodigoAdmision);
                    detmast.get(i).Shipment_Code__c=lisresp.NumeroEnvio;
                    detmast.get(i).Enviado_a_Correo__c=true;
                    contador++;
                }catch(Exception e){
                    system.debug('e'+e);
                }
                system.debug('contador'+contador);
            }
        }
        if(contador>0){
            update detmast;
        }
        
        if(integer.valueOf(fin)<detmast.size()){
            integer total=detmast.size();
            integer i=integer.valueOf(fin)+1;
            integer f=integer.valueOf(fin)+50;
            system.debug('total'+total);
            system.debug('i'+i);
            system.debug('f'+f);
            if(f>total){
                f=f-(f-total);
            }
            string url='/apex/HE_AdmicionCEP_envia_a_correos?id='+idmaster+'&&in='+i+'&&fn='+f;
            system.debug('url'+url);
            inicio=string.valueOf(i);
            fin=string.valueOf(f);
            pageReference p = new PageReference(url);
            p.setRedirect(true);
            return  p;
        }else{
            
            detmast=[select Id, Name, Master__c, Order_Number__c, Type_of_Mail__c, Vendedor__c, Shipper_Address__c, Shipper_Town__c, Consignatario__c, 
                     Direccion_Consignatario__c, Comuna__c, Postal_Code__c, Consignee_Phone__c, Pieces__c, Peso__c, Valor__c, Puerto_de_Destino__c,
                     Destination_Generic_Postal_Code__c, Client_Code__c, HD_PUDO__c, Undelivered_Parcels__c, Postal_Services__c, Descripcion__c,Direccion_Normalizada__c,
                     Nombre_Cod_Arancelario__c, Estado_Guia__c, Cod_Arancelario__c, Factor_Peso__c, Factor_Pieces__c, Tarifa_Guia__c, Bag_Code__c 
                     FROM Detalles_Master__c WHERE id='a050v000002dS9O'/*Master__c=:idmaster*/and Enviado_a_Correo__c=false order by id];  
            
            for(integer j=0;j<detmast.size();j++){ 
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, ' guias no normalizada '+ detmast.get(j).Name + 'direccion incorrecta'+ detmast.get(j).Direccion_Consignatario__c );
                ApexPages.addMessage(msg);
                
                
            }
            if(detmast.size()==0){
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Todas guias han sido cargadas. ' );
                ApexPages.addMessage(msg);
            }
        }
        
        return null;
    }
    
    
    
    public PageReference genera_CSV_Correos(){
        
        system.debug('entro a normalizacion');
        system.debug('inicio'+inicio);
        system.debug('fin'+fin);
          system.debug('idmaster'+idmaster);
        
        
        Master__c   mt=[select Id, Name, Fecha_Recepcion__c, Estado__c, N_Manifiesto_Aduana__c, Cuenta__c, Total_Valor__c, Total_Peso__c, Total_Piezas__c,
                        Aeropuerto_Origen__c, Aeropuerto_Destino__c, N_Vuelo__c, Total_Cajas__c, Master_AirwayBill__c, Fecha_Vuelo__c
                        from Master__c  where id=:idmaster];
        system.debug('mt'+mt);
        list<Detalles_Master__c> detmast=[select Id, Name, Master__c, Order_Number__c, Type_of_Mail__c, Vendedor__c, Shipper_Address__c, Shipper_Town__c, Consignatario__c, 
                                          Direccion_Consignatario__c, Comuna__c, Postal_Code__c, Consignee_Phone__c, Pieces__c, Peso__c, Valor__c, Puerto_de_Destino__c,Rut_Consignatario__c,
                                          Destination_Generic_Postal_Code__c, Client_Code__c, HD_PUDO__c, Undelivered_Parcels__c, Postal_Services__c, Descripcion__c,Direccion_Normalizada__c,
                                          Nombre_Cod_Arancelario__c, Estado_Guia__c, Cod_Arancelario__c, Factor_Peso__c, Factor_Pieces__c, Tarifa_Guia__c, Bag_Code__c ,Consignee_Email__c,Master__r.Name
                                          FROM Detalles_Master__c WHERE  Master__c=:idmaster and Direccion_Normalizada__c=true order  by id];
        system.debug('detmast'+detmast);
        string header= 'Referencia;Nombre;Dirección;ComunaDestinataTTTio;Pais;Producto;Porte;Bultos;Contenido;Valor;Peso;Volumen;Direccion Remitente;ComunaTTTemitente;ObseTTTvaciones;FactuTTTa;Telefono;Mail'+'\n';
        string finalstr =header;
        for(Detalles_Master__c dt: detmast){    
            
            string Referencia=dt.name;
            string Nombre=dt.Consignatario__c;
            string Direccion=dt.Direccion_Consignatario__c;
            string ComunaDestinataTTTio=dt.Comuna__c;
            string Pais='56';
            string Producto='24';
            string Porte='p';
            string Bultos='1';//string.valueOf(dt.Pieces__c);
            string Contenido=dt.Descripcion__c;
            string Valor=string.valueOf(dt.Valor__c);
            string Peso=string.valueOf(dt.Peso__c);
            string Volumen='1'; 
            string Direccion_Remitente=dt.Shipper_Address__c;
            string ComunaTTTemitente=dt.Shipper_Town__c;
            string ObseTTTvaciones='0';
            string FactuTTTa='0';
            string Telefono=dt.Consignee_Phone__c;
            string Mail=dt.Consignee_Email__c;
            
            
            string recordString = Referencia+';'+Nombre+';'+Direccion+';'+ComunaDestinataTTTio+';'+Pais+';'+Producto+';'+Porte+';'+Bultos+';'+Contenido+';'+Valor+';'+Peso+';'+Volumen+';'+Direccion_Remitente+';'+ComunaTTTemitente+';'+ObseTTTvaciones+';'+FactuTTTa+';'+Telefono+';'+Mail+'\n';  
            finalstr = finalstr +recordString;
        }   
        blob csvBlob = Blob.valueOf(finalstr);
        Attachment csv=new Attachment();
        csv.Body=csvBlob;
        csv.ParentId=mt.id;
        csv.Name='correos_de_chile.csv';
        insert csv;
        
        
        pageReference p = new PageReference('/'+mt.id);
        return p; 
        
        
    }
    public PageReference redirecion(){
        list<Detalles_Master__c> detmast=[select Id  FROM Detalles_Master__c WHERE  Master__c=:idmaster and Direccion_Normalizada__c=true order by id];
        totalenvios=string.valueOf(detmast.size());
        if(detmast.size()<integer.valueOf(fin)){
            fin=string.valueOf(detmast.size());
        }
        return null;
    }
    
    
    
}