force-app/main/default/objects/Detalles_Master__c/fields/Dolar_Dia__c.field-meta.xml
<CustomField>
    <fullName>Dolar_Dia__c</fullName>
    <label>Dolar Día</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Estado_Aduana__c.field-meta.xml
<CustomField>
    <fullName>Estado_Aduana__c</fullName>
    <label>Estado Aduana</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Estado_Correo__c.field-meta.xml
<CustomField>
    <fullName>Estado_Correo__c</fullName>
    <label>Estado Correo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Estado_Guia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Guia__c</fullName>
    <label>Estado Guía</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documental</fullName>
            </value>
            <value>
                <fullName>Menor a 30</fullName>
            </value>
            <value>
                <fullName>Facturada</fullName>
            </value>
            <value>
                <fullName>Abandonado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Retenido por RUT</fullName>
            </value>
            <value>
                <fullName>Retenido por Aduana</fullName>
            </value>
            <value>
                <fullName>Retenido por Visación</fullName>
            </value>
            <value>
                <fullName>Retenido en escaner</fullName>
            </value>
            <value>
                <fullName>En cadena de custodia</fullName>
            </value>
            <value>
                <fullName>Paquete No Recibido</fullName>
            </value>
            <value>
                <fullName>Retenido por error ISP</fullName>
            </value>
            <value>
                <fullName>Retenido por peso</fullName>
            </value>
            <value>
                <fullName>Sobrante</fullName>
            </value>
            <value>
                <fullName>Alto valor</fullName>
            </value>
            <value>
                <fullName>RUT no conseguido Retenido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Fecha_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Entrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <label>Master</label>
    <referenceTo>Master__c</referenceTo>
    <relationshipName>Detalles_Manifiestos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HE_Facturar_Controller.cls
global class HE_Facturar_Controller {
    
       global  HE_Facturar_Controller(){
       
    }
    @RemoteAction
    global static String facturar(double dolar,string fechaIn , string FechaFin ){
        system.debug('dolar'+dolar);
        system.debug('FechaFin'+FechaFin);
        system.debug('fechaIn'+fechaIn);
        string[] fechai=fechaIn.split('-');
          string[] fechaf=fechaIn.split('-');
        date FF=date.valueOf(fechaf[2]+'-'+fechaf[1]+'-'+fechaf[0]);
        date FI=date.valueOf(fechai[2]+'-'+fechai[1]+'-'+fechai[0]);
        system.debug('FF'+FF);
        system.debug('FI'+FI);
         list<Detalles_Master__c>  listafacturar;
        if(!test.isRunningTest()){
        listafacturar=[SELECT Id, Name, Master__c, Fecha_de_Entrega__c, Estado_Correo__c, Estado_Aduana__c, Estado_Guia__c,Dolar_Dia__c
                                                 FROM Detalles_Master__c where (Estado_Guia__c='Documental' or Estado_Guia__c='	Menor a 30' )  
                                                 and Fecha_de_Entrega__c>=:FI and Fecha_de_Entrega__c<=:FF and Estado_Correo__c='ENVIO ENTREGADO' ];
        }else{
        listafacturar=[SELECT Id, Name, Master__c, Fecha_de_Entrega__c, Estado_Correo__c, Estado_Aduana__c, Estado_Guia__c,Dolar_Dia__c
                                                 FROM Detalles_Master__c];
            
        }
       
            if(listafacturar.size()>0){
            for(integer i=0; i<listafacturar.size();i++){
                listafacturar.get(i).Dolar_Dia__c=dolar;
                listafacturar.get(i).Estado_Guia__c='Facturada';
            }
            // update listafacturar;
            return 'se facturaron '+listafacturar.size()+' filas';  
        }else{
            return 'no existen lineas que puedan ser facturadas';    
        }
        
    }
}