force-app/main/default/objects/Detalles_Master__c/fields/Estado_Correo__c.field-meta.xml
<CustomField>
    <fullName>Estado_Correo__c</fullName>
    <label>Estado Correo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Fecha_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Entrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Nombre_Receptor__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Receptor__c</fullName>
    <label>Nombre Receptor</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Rut_Consignatario__c.field-meta.xml
<CustomField>
    <fullName>Rut_Consignatario__c</fullName>
    <label>Rut Consignatario</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalles_Master__c/fields/Shipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Code__c</fullName>
    <description>Código de envío</description>
    <label>Shipment Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndPoint__mdt/fields/Codigo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Cliente__c</fullName>
    <label>Codigo Cliente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndPoint__mdt/fields/contrase_a__c.field-meta.xml
<CustomField>
    <fullName>contrase_a__c</fullName>
    <label>contraseña</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndPoint__mdt/fields/usuario__c.field-meta.xml
<CustomField>
    <fullName>usuario__c</fullName>
    <label>usuario</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historial_de_Tracking__c/fields/Detalles_Master__c.field-meta.xml
<CustomField>
    <fullName>Detalles_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detalles Master</label>
    <referenceTo>Detalles_Master__c</referenceTo>
    <relationshipLabel>Historiales de Tracking</relationshipLabel>
    <relationshipName>Historiales_de_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historial_de_Tracking__c/fields/Estado_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Estado_Tracking__c</fullName>
    <label>Estado Tracking</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historial_de_Tracking__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historial_de_Tracking__c/fields/Oficina_de_Origen__c.field-meta.xml
<CustomField>
    <fullName>Oficina_de_Origen__c</fullName>
    <label>Oficina de Origen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historial_de_Tracking__c/fields/Shipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Code__c</fullName>
    <formula>Detalles_Master__r.Shipment_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipment Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HE_consulta_estado.cls
public class HE_consulta_estado {
    public list<tempuriOrg.Estruct_Envio> listado_estado{get;set;}
    public HE_consulta_estado(ApexPages.StandardController controller){
        
    }
    public PageReference consulta() {
        String ido = ApexPages.currentPage().getParameters().get('id');
        tempuriOrg    ter=new  tempuriOrg();
        tempuriOrg.ConsultaEnvioResponse_element   rest = new tempuriOrg.ConsultaEnvioResponse_element();
        tempuriOrg.EnvioReq   emp =  new tempuriOrg.EnvioReq();
        tempuriOrg.EnvioRes  resp  =  new tempuriOrg.EnvioRes();
        EndPoint__mdt ep=[SELECT Id, usuario__c, contrase_a__c, Codigo_Cliente__c, Label FROM EndPoint__mdt where Label='tempuriOrg' limit 1 ];
        Detalles_Master__c detord = [SELECT Nombre_Receptor__c, Fecha_de_Entrega__c, Rut_Consignatario__c, Estado_Correo__c,Shipment_Code__c , Id, Name FROM Detalles_Master__c where  id=:ido];
         //emp.Codigo='999023520749';
         emp.CodigoCliente='532878';
         emp.Usuario='PRUEBATRAZABILIDAD';
        emp.Password='P2RTRAZ19'; 
         emp.Codigo=detord.Shipment_Code__c==null?detord.Name:detord.Shipment_Code__c;//'999023520749';
         //emp.CodigoCliente=ep.Codigo_Cliente__c;
        // emp.Usuario=ep.usuario__c;
       //  emp.Password=ep.contrase_a__c; 
        system.debug('emp'+emp);
        tempuriOrg.WSConsultaEnvioSoap temWS =  new tempuriOrg.WSConsultaEnvioSoap();
        
        if(!test.isRunningTest()){
            resp=temWS.ConsultaEnvio(emp);
        }else{
            
            tempuriOrg.Estruct_Historial eh=new tempuriOrg.Estruct_Historial();
            
            eh.HisFecha='22/03/2017 17:00';
            eh.HisEstadoDes='stg';
            eh.HisOficinaOrigenDes='stg';
            list<tempuriOrg.Estruct_Historial> dd=new list<tempuriOrg.Estruct_Historial>();
            dd.add(eh);
            tempuriOrg.ArrayOfEstruct_Historial His=new  tempuriOrg.ArrayOfEstruct_Historial();
            His.Estruct_Historial=dd;
            tempuriOrg.Estruct_Envio  ee=new tempuriOrg.Estruct_Envio();
            ee.Envio='1';
            ee.FechaEntrega='22/03/2017';
            ee.NombreEntrega='1';
            ee.RutEntrega='2';
            ee.Estado='3';
            ee.Referencia='4';
            ee.HistorialLen=0;
            ee.Historial=His;
            
            list<tempuriOrg.Estruct_Envio>  ff=new list<tempuriOrg.Estruct_Envio>();
            ff.add(ee);
            tempuriOrg.ArrayOfEstruct_Envio En=new     tempuriOrg.ArrayOfEstruct_Envio();
            en.Estruct_Envio=ff;
            
            
            tempuriOrg.EnvioRes er=new tempuriOrg.EnvioRes();
            er.Envio=en;
            er.Largo=1;
            er.Indice=1;
            er.TipoError='sdff';
            resp=er;
        }
        
        list<Historial_de_Tracking__c> histrack= [SELECT Id, Fecha__c, Estado_Tracking__c, Oficina_de_Origen__c, Name,Detalles_Master__c  FROM Historial_de_Tracking__c where Detalles_Master__c =:detord.id];
        if(histrack.size()>0){
            // delete histrack;
            if(resp.Envio.Estruct_Envio[0].Historial!=null ){
                if(resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial!=null ){
                   
                    for(integer i=0;i<resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial.size();i++){
                        integer contador=0;
                          Historial_de_Tracking__c  ht=new Historial_de_Tracking__c();
                       for(Historial_de_Tracking__c  htc:histrack){      
                        datetime fecha=datetime.parse(resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisFecha);
                        system.debug('fecha'+fecha);
                        if(fecha!=htc.Fecha__c){
                          
                            ht.Estado_Tracking__c=resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisEstadoDes;
                            system.debug('resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisFecha'+resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisFecha); 
                            ht.Fecha__c=fecha;
                            ht.Oficina_de_Origen__c=resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisOficinaOrigenDes;
                            ht.Detalles_Master__c=detord.id;
                            ht.Name=detord.Name;
                          
                        }else{
                            contador++;
                        }
                         }
                        if(contador==0){
                              insert ht;
                        }
                    
                    }
                }
                }
            
        }else{
            system.debug('resp.Envio.Estruct_Envio[0].Historial'+resp.Envio.Estruct_Envio[0].Historial);
            if(resp.Envio.Estruct_Envio[0].Historial!=null){
                 if(resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial!=null){
                for(integer i=0;i<resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial.size();i++){
                    Historial_de_Tracking__c  ht=new Historial_de_Tracking__c();
                    ht.Estado_Tracking__c=resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisEstadoDes;
                    system.debug('resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisFecha'+resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisFecha);
                    datetime fecha=datetime.parse(resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisFecha);
                    system.debug('fecha'+fecha);
                    ht.Fecha__c=fecha;
                    ht.Oficina_de_Origen__c=resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial[i].HisOficinaOrigenDes;
                    ht.Detalles_Master__c=detord.id;
                    ht.Name=detord.Name;
                    insert ht;
                }
                 }
            }
        }
        detord.Nombre_Receptor__c=resp.Envio.Estruct_Envio[0].NombreEntrega;
        
        system.debug('resp.Envio.Estruct_Envio[0].FechaEntrega'+resp.Envio.Estruct_Envio[0].FechaEntrega);        
        //datetime fecha_entrega=date.parse();
        detord.Fecha_de_Entrega__c=resp.Envio.Estruct_Envio[0].FechaEntrega==''?null:date.parse(resp.Envio.Estruct_Envio[0].FechaEntrega);
        detord.Rut_Consignatario__c=resp.Envio.Estruct_Envio[0].RutEntrega;
        detord.Estado_Correo__c=resp.Envio.Estruct_Envio[0].Estado;
        detord.Shipment_Code__c=resp.Envio.Estruct_Envio[0].Envio;
        update detord;
        
        system.debug('resp'+resp); 
        system.debug('resp.Envio'+resp.Envio);
        system.debug('resp'+resp.Envio.Estruct_Envio);
        system.debug('resp'+resp.Envio.Estruct_Envio.size());
        system.debug('resp'+resp.Envio.Estruct_Envio[0].Historial);
        system.debug('resp'+resp.Envio.Estruct_Envio[0].Historial.Estruct_Historial);
        //  listado_estado=resp.Envio.Estruct_Envio;
        pageReference p = new PageReference('/'+detord.id);
        
        
        return p;
    } 
    
    /* public static resServicio parseResponse(HttpResponse res){
resServicio r = new resServicio();
dom.Document resDoc = res.getBodyDocument();
dom.XmlNode envelope = resDoc.getRootElement();*/
    /*System.debug(envelope);
dom.XmlNode envB = envelope.getChildElement('Body', 'http://schemas.xmlsoap.org/soap/envelope/');
dom.XmlNode bRes = envB.getChildElement('rechazoPropuestaResponse', 'http://ws.centralizadorinspecciones.integracion.cns.cl/');
dom.XmlNode ret = bRes.getChildElement('return', null);*/
    /*  r.mensajeRespuesta = envelope.getChildElement('mensajeRespuesta', null).getText();
r.numRespuesta = envelope.getChildElement('numRespuesta', null).getText();
System.debug('Mensaje respuesta: '+r.mensajeRespuesta);
System.debug('Numero respuesta: '+r.numRespuesta);
return r;
}*/
}