force-app/main/default/objects/Direcciones__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direcciones__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Agente__c.field-meta.xml
<CustomField>
    <fullName>Agente__c</fullName>
    <label>Agente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fedex</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Nacional</fullName>
            </value>
            <value>
                <fullName>Hot Express</fullName>
            </value>
            <value>
                <fullName>Proyecto</fullName>
            </value>
            <value>
                <fullName>Servicio Carga</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
            <value>
                <fullName>TNT Nacional</fullName>
            </value>
            <value>
                <fullName>FEDEX IPF</fullName>
            </value>
            <value>
                <fullName>MDZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <formula>Direccion_Destinatario__r.Direccion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calle</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Compania_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Compania_Destinatario__c</fullName>
    <label>Compañía Destinatario</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Direccion_Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Destinatario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre Dirección</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Direcciones__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ID_Remitente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Direcciones__c</referenceTo>
    <relationshipLabel>Guías de Exportación</relationshipLabel>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Estado_Guia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Guia__c</fullName>
    <label>Estado Guía</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/ID_Remitente__c.field-meta.xml
<CustomField>
    <fullName>ID_Remitente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID Remitente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Solicitudes_de_Pickup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/N_de_Guia__c.field-meta.xml
<CustomField>
    <fullName>N_de_Guia__c</fullName>
    <label>Etiqueta Agente</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <formula>Direccion_Destinatario__r.Pais__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Proposito_del_Envio__c.field-meta.xml
<CustomField>
    <fullName>Proposito_del_Envio__c</fullName>
    <label>Propósito del Envío</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Efectos Personales</fullName>
            </value>
            <value>
                <fullName>Documento</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>No Vendido</fullName>
            </value>
            <value>
                <fullName>Regalo</fullName>
            </value>
            <value>
                <fullName>Reparar y Devolver</fullName>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
            <value>
                <fullName>Muestra sin valor Comercial</fullName>
            </value>
            <value>
                <fullName>Regalo a China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guias_de_Exportacion__c/fields/Solicitud_de_Retiro__c.field-meta.xml
<CustomField>
    <fullName>Solicitud_de_Retiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solicitud de Retiro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Solicitud_de_Retiro__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ID_Remitente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Solicitud_de_Retiro__c</referenceTo>
    <relationshipLabel>Guías de Exportación</relationshipLabel>
    <relationshipName>Gu_as_de_Exportaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Cantidad_Paquetes__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Paquetes__c</fullName>
    <label>Cantidad Paquetes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Contacto_para_Retiro__c.field-meta.xml
<CustomField>
    <fullName>Contacto_para_Retiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto para Retiro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Solicitudes de Retiro</relationshipLabel>
    <relationshipName>Solicitudes_de_Retiro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Solicitudes de Retiro</relationshipLabel>
    <relationshipName>Solicitudes_de_Retiro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Direcciones__c.field-meta.xml
<CustomField>
    <fullName>Direcciones__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direcciones</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Direcciones__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Direcciones__c</referenceTo>
    <relationshipLabel>Solicitudes de Retiro</relationshipLabel>
    <relationshipName>Solicitudes_de_Retiro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Estado_Solicitud__c.field-meta.xml
<CustomField>
    <fullName>Estado_Solicitud__c</fullName>
    <label>Estado Solicitud</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Retirado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Etapa__c.field-meta.xml
<CustomField>
    <fullName>Etapa__c</fullName>
    <label>Etapa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Validado Customer Service</fullName>
            </value>
            <value>
                <fullName>Recibido Operaciones</fullName>
            </value>
            <value>
                <fullName>Asignado a Mensajero</fullName>
            </value>
            <value>
                <fullName>Recibido por Mensajero</fullName>
            </value>
            <value>
                <fullName>Retirado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Fecha_de_Retiro__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Retiro__c</fullName>
    <label>Fecha de Retiro</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Hora_Desde__c.field-meta.xml
<CustomField>
    <fullName>Hora_Desde__c</fullName>
    <label>Hora Desde</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Hora_Hasta__c.field-meta.xml
<CustomField>
    <fullName>Hora_Hasta__c</fullName>
    <label>Hora Hasta</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Indicaciones_Especiales__c.field-meta.xml
<CustomField>
    <fullName>Indicaciones_Especiales__c</fullName>
    <label>Indicaciones Especiales</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Peso_Aproximado__c.field-meta.xml
<CustomField>
    <fullName>Peso_Aproximado__c</fullName>
    <label>Peso Aproximado (Kg)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Rango_Horario__c.field-meta.xml
<CustomField>
    <fullName>Rango_Horario__c</fullName>
    <label>Rango Horario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10:30 - 11:30</fullName>
            </value>
            <value>
                <fullName>11:30 - 12:30</fullName>
            </value>
            <value>
                <fullName>12:30 - 13:30</fullName>
            </value>
            <value>
                <fullName>13:30 - 14:30</fullName>
            </value>
            <value>
                <fullName>14:30 - 15:30</fullName>
            </value>
            <value>
                <fullName>15:30 - 16:30</fullName>
            </value>
            <value>
                <fullName>16:30 - 17:30</fullName>
            </value>
            <value>
                <fullName>10:00 - 14:00</fullName>
            </value>
            <value>
                <fullName>10:00 - 17:30</fullName>
            </value>
            <value>
                <fullName>14:00 - En adelante</fullName>
            </value>
            <value>
                <fullName>10:00 - En adelante</fullName>
            </value>
            <value>
                <fullName>Todo el día</fullName>
            </value>
            <value>
                <fullName>Hasta las 18:00</fullName>
            </value>
            <value>
                <fullName>Hasta las 14:00</fullName>
            </value>
            <value>
                <fullName>14:00 - 17:30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solicitud_de_Retiro__c/fields/Tipo_de_Paquete__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Paquete__c</fullName>
    <label>Tipo de Paquete</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sobre</fullName>
            </value>
            <value>
                <fullName>Caja</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HE_Mis_Documentos.cls
public class HE_Mis_Documentos {
    public string idp {get;set;}
    public string idc {get;set;}
    public string resultJSON {get;set;} 
    public string resultJSON2 {get;set;} 
    public list<Guias_de_Exportacion__c> guiexp {get;set;}
    public list<Solicitud_de_Retiro__c> solret {get;set;}
    Map<string, Attachment> attachments {get;set;}
    
    public PageReference datos(){
        system.debug('datos');
        system.debug('idp '+ ApexPages.currentPage().getParameters().get('idp'));
        system.debug('idc '+ ApexPages.currentPage().getParameters().get('idc'));
        idp=ApexPages.currentPage().getParameters().get('idp');
        idc=ApexPages.currentPage().getParameters().get('idc');
        
        
        listguia();
        
        return null; 
    }
    
    public pagereference listguia(){
        guiexp=[SELECT Id, Name,N_de_Guia__c,ID_Remitente__r.name,Direccion_Destinatario__r.name,Pais__c,calle__c,CreatedDate,
                Estado_Guia__c,Agente__c,Compania_Destinatario__c,Proposito_del_Envio__c
                FROM Guias_de_Exportacion__c  where ID_Remitente__c=:idp order by Name DESC ];

        //RCG: Se agrega filtro para traer Solicitud_de_Retiro__c de hasta 2 años atrás - 23/05/2025 Ticket Seidor N°00023071
        Date haceDosAnios = Date.today().addYears(-2);
        
        solret=[SELECT Id, Name, Direcciones__c, Cuenta__c, Hora_Desde__c, Hora_Hasta__c, Fecha_de_Retiro__c, Contacto_para_Retiro__c,
                Indicaciones_Especiales__c, Etapa__c, Estado_Solicitud__c, Rango_Horario__c, Cantidad_Paquetes__c, Peso_Aproximado__c,
                Tipo_de_Paquete__c,Direcciones__r.name
                FROM Solicitud_de_Retiro__c where Cuenta__c=:idc AND CreatedDate >=: haceDosAnios];
        
        system.debug('solret'+solret);
        return null;
    }
    
    
    public void consultarguias(){
        //usuario del site y metadata
        User user = [select id from user where name = 'cliente Usuario invitado al sitio Web' limit 1];
        Endpoint__mdt endpoint = [select url__c from EndPoint__mdt where label = 'Url descarga archivos' limit 1];
        
        String nguia = ApexPages.currentPage().getParameters().get('guia');
        String fecha_inicio = ApexPages.currentPage().getParameters().get('fi');
        String fecha_fin = ApexPages.currentPage().getParameters().get('fn');
        String idc = ApexPages.currentPage().getParameters().get('idc');
        
        string fi;
        string fn;
        
        
        if(fecha_inicio!='' && fecha_inicio!=null){
            fi = fecha_inicio+'T00:00:00.000+0000';
        }
        if(fecha_fin!='' && fecha_fin!=null){
            fn =fecha_fin+'T23:59:59.000+0000';
        }
        string consulta='';
        if((nguia!='' && nguia!=null) || 
           (fecha_fin!='' && fecha_fin!=null && fecha_fin!='' && fecha_fin!=null )){
               if((nguia!='' && nguia!=null)){
                   consulta+=' AND Name=\''+nguia+'\'';
               }
               if((fecha_fin!='' && fecha_fin!=null && fecha_fin!='' && fecha_fin!=null )){
                   consulta+=' AND (CreatedDate>='+fi+' AND CreatedDate<='+fn+' )';    
               }
           }
        
        system.debug('guia'+nguia);
        system.debug('fecha_inicio'+fecha_inicio);
        system.debug('fecha_fin'+fecha_fin);
        system.debug('idp'+idp);
        system.debug('idc'+idc);
        system.debug('consulta'+consulta);

        string  query='SELECT Id, Name,N_de_Guia__c,CreatedDate,Agente__c,ID_Remitente__r.name,ID_Remitente__r.ShippingAddress,'+
            ' Direccion_Destinatario__r.name,Pais__c,Proposito_del_Envio__c,ID_Remitente__c,'+
            ' Estado__c,Estado_Guia__c,Fecha_Ultimo_Estado__c,Fecha_de_Envio__c,Calle__c, ID_Remitente__r.ShippingStreet,'+
            ' ID_Remitente__r.ShippingCity, ID_Remitente__r.ShippingState, ID_Remitente__r.ShippingCountry, Centro_de_Costo__c '+
            ' FROM Guias_de_Exportacion__c '+
            ' where ID_Remitente__c=\''+idc+'\' '+consulta+
            ' order by CreatedDate DESC';
        
        system.debug('query='+query);
        List<Guias_de_Exportacion__c> guiexp = Database.query(query);                
        
        //-----carga lista de guias
        Set<Guias_de_Exportacion__c> guideList = new Set<Guias_de_Exportacion__c>(guiexp);														
        /*for (Guias_de_Exportacion__c  guide : guiexp) {
            guideList.add(guide.Id);             
        }*/
        //listado de adjuntos de lista de guias segun id
        attachments = new Map<string, Attachment>([SELECT parentId FROM Attachment WHERE parentId IN : guideList AND createdbyId =: user.Id]);
        
        system.debug('guideList size='+guideList.size());
        system.debug('attachments size='+attachments.size());
        system.debug('guiexp='+guiexp.size());
        //-----carga lista de guias
        
        Attachment attachment;
        string det_guiexp='[';
        for(integer i=0;i<guiexp.size();i++){
                        
            if(i!=0){
                det_guiexp+=','; 
            } 
            string dir;
            if(guiexp[i].Direccion_Destinatario__r.name!=null){
                
                dir=guiexp[i].Direccion_Destinatario__r.name.replace('"','').replace('	','');
                system.debug('dir');
            }                  
            
            //leer adjuntos y comparar la guia, si coincice
            for (String attachmentId : attachments.keySet()){
                attachment = attachments.get(attachmentId);
                if(attachment.ParentId == guiexp[i].id){
                    break;
                }
                attachment = null;
            }
                        
            system.debug('attachment size='+attachment);
            system.debug('guiexp[i].id='+guiexp[i].id);
            
            det_guiexp+='{';            
            det_guiexp+='"Estado_Guia__c":"'+guiexp[i].Estado_Guia__c+'",';
            det_guiexp+='"Name":"'+guiexp[i].Name+'",';
            det_guiexp+='"N_de_Guia__c":"'+guiexp[i].N_de_Guia__c+'",';
            det_guiexp+='"Agente__c":"'+guiexp[i].Agente__c+'",';
            det_guiexp+='"CreatedDate":"'+guiexp[i].CreatedDate+'",'; 
            det_guiexp+='"Direccion_Destinatario__name":"'+dir+'",';
            det_guiexp+='"Pais__c":"'+guiexp[i].Pais__c+'",';            
            det_guiexp+='"Proposito_del_Envio__c":"'+guiexp[i].Proposito_del_Envio__c+'",';
            det_guiexp+='"Centro_de_Costo__c":"'+guiexp[i].Centro_de_Costo__c+'",';
            det_guiexp+='"id":"' + guiexp[i].id + '",';    
            if(attachment != null){
                det_guiexp+='"attachmentId":"'+ attachment.Id +'",';
                det_guiexp+='"attachmentUrl":"'+ endpoint.url__c.replace('{ID}', attachment.Id) +'"';
            }
            else{
                det_guiexp+='"attachmentId":"",';
                det_guiexp+='"attachmentUrl":""';
            }
            det_guiexp+='}';
        }
        det_guiexp+=']';
        det_guiexp=det_guiexp.replace('null', '');
        system.debug('det_guiexp='+det_guiexp);
        resultJSON='{"success":true, "guias":'+det_guiexp+'}';   
        resultJSON = resultJSON.replace('\r\n',' ').replace('\n',' ').replace('\r',' ').replace('\r\n',' ').replace('\n\r',' ').replace('\t',' ');
    }    
    
    /*public string getAttachment(string parentId, string userId){        
        List<Attachment> attachments = new List<Attachment>();
        attachments = [select id from Attachment where parentId =: parentId and createdbyId =: userId];
        if(attachments.size() > 0){
            return attachments[0].id;
        }
        else{
            return '';
        }
    }*/
}